added expect to containt and upgrading cuttting with bash expresisons

diff --git a/struct_testing b/struct_testing
--- a/struct_testing
+++ b/struct_testing
@@ -274,7 +274,11 @@ PURPLE_BLUE="\033[38;5;93m"
 BRIGHT_BLUE87="\033[38;5;87m"
 
 YELLOW_OVER_DARKBLUE="\033[38;5;220m\033[48;5;20m"
+YELLOW_OVER_GRAY241="\033[38;5;220m\033[48;5;241m"
 YELLOW_OVER_DARKBLUE2="\033[38;5;11m\033[48;5;18m"
+LIGHTPINK_OVER_DARKBLUE="\033[38;5;204m\033[48;5;21m"
+DARK_BLUE_OVER_PEACH="\033[38;5;20m\033[48;5;208m"
+
 
 RESET="\033[0m"
 CERO="\033[01;0m"
@@ -401,7 +405,7 @@ CERO="\033[01;0m"
 
 
         function Testing() {
-            echo -e "${GRAY} Testing ${PURPLE}${1}${GREEN}, ${RED}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
+            echo -e "${CYAN} Testing ${PURPLE}${1}${GREEN}, ${RED}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
         } # end Testing
         alias testing=Testing
 
@@ -1203,49 +1207,76 @@ CERO="\033[01;0m"
             #     expect $(echo "hola") not "hello"
             #     expect $(echo "hola") ≠ "hello"
             #       0       1            2  3   4     5
-            local statement=$(echo """${@}""")
+            local statement=""
+            statement="""${@}"""
                 #| sed 's/'"="'/3QU4L51GN/g' \
                 #| sed 's/'"!"'/3XCL4M4T10N/g' \
-            local inputo=$(echo """${@}""" \
-                | sed 's/'"not to be equal to"'/!/g' \
-                | sed 's/'"to not be equal to"'/!/g' \
-                | sed 's/'"to be not equal to"'/!/g' \
-                | sed 's/'"to be equal not to"'/!/g' \
-                | sed 's/'"not to be equal"'/!/g' \
-                | sed 's/'"to not be equal"'/!/g' \
-                | sed 's/'"to be not equal"'/!/g' \
-                | sed 's/'"not to equal"'/!/g' \
-                | sed 's/'"to not equal"'/!/g' \
-                | sed 's/'"to equal not"'/!/g' \
-                | sed 's/'"not to be"'/!/g' \
-                | sed 's/'"to not be"'/!/g' \
-                | sed 's/'"to be not"'/!/g' \
-                | sed 's/'"not be"'/!/g' \
-                | sed 's/'"be not"'/!/g' \
-                | sed 's/'"not"'/!/g' \
+            (( DEBUG )) && echo -e "0.${RED}${FUNCNAME[1]} that value ${RED},,${CYAN}${statement}${RED}''${RESET}"
+            # exit 0
+            local inputo=""
+            inputo=$(echo """${statement}""" \
+                | sed 's/'"="'//g' \
+                | sed 's/'"!"'//g' \
+                | sed 's/'"~"'//g' \
+                | sed 's/'" to not be the same as "'/!/g' \
+                | sed 's/'" to not be the same as "'/!/g' \
+                | sed 's/'" not same as "'/!/g' \
+                | sed 's/'" not to be equal to "'/!/g' \
+                | sed 's/'" to not be equal to "'/!/g' \
+                | sed 's/'" to be not equal to "'/!/g' \
+                | sed 's/'" to be equal not to "'/!/g' \
+                | sed 's/'" not to be equal "'/!/g' \
+                | sed 's/'" to not be equal "'/!/g' \
+                | sed 's/'" to be not equal "'/!/g' \
+                | sed 's/'" not to equal "'/!/g' \
+                | sed 's/'" to not equal "'/!/g' \
+                | sed 's/'" to equal not "'/!/g' \
+                | sed 's/'" not to be "'/!/g' \
+                | sed 's/'" to not be "'/!/g' \
+                | sed 's/'" to be not "'/!/g' \
+                | sed 's/'" not be "'/!/g' \
+                | sed 's/'" be not "'/!/g' \
+                | sed 's/'" not "'/!/g' \
+                | sed 's/'" ≠ "'/!/g' \
                 | sed 's/'"≠"'/!/g' \
+                | sed 's/'" !! "'/!/g' \
                 | sed 's/'"!!"'/!/g' \
                 | sed 's/'"!!"'/!/g' \
-                | sed 's/'"!!"'/!/g' \
-                | sed 's/'"to be equal to"'/=/g' \
-                | sed 's/'"to be equal"'/=/g' \
-                | sed 's/'"to equal to"'/=/g' \
-                | sed 's/'"to equal"'/=/g' \
-                | sed 's/'"be equal to"'/=/g' \
-                | sed 's/'"be equal"'/=/g' \
-                | sed 's/'"to be"'/=/g' \
-                | sed 's/'"be"'/=/g' \
+                | sed 's/'" to be the same as "'/=/g' \
+                | sed 's/'" same as "'/=/g' \
+                | sed 's/'" to be equal to "'/=/g' \
+                | sed 's/'" to be equal "'/=/g' \
+                | sed 's/'" to equal to "'/=/g' \
+                | sed 's/'" to equal "'/=/g' \
+                | sed 's/'" be equal to "'/=/g' \
+                | sed 's/'" be equal "'/=/g' \
+                | sed 's/'" to be "'/=/g' \
+                | sed 's/'" be "'/=/g' \
+                | sed 's/'" == "'/=/g' \
+                | sed 's/'" == "'/=/g' \
                 | sed 's/'"=="'/=/g' \
-                | sed 's/'"=="'/=/g' \
-                | sed 's/'"=="'/=/g' \
+                | sed 's/'" include "'/~/g' \
+                | sed 's/'" includes "'/~/g' \
+                | sed 's/'" to include "'/~/g' \
+                | sed 's/'" to have included "'/~/g' \
+                | sed 's/'" to have contained "'/~/g' \
+                | sed 's/'" to contains "'/~/g' \
+                | sed 's/'" to contain "'/~/g' \
+                | sed 's/'" contains "'/~/g' \
+                | sed 's/'" contain "'/~/g' \
+                | sed 's/'" ~~ "'/~/g' \
+                | sed 's/'" ~~ "'/~/g' \
+                | sed 's/'"~~"'/~/g' \
             )
+            (( DEBUG )) && echo -e "0.${RED}${FUNCNAME[1]} inputo ${RED},,${GREEN}${inputo}${RED}''${RESET}"
             # echo $inputo
             # return 0
             #    0     1    2   3
             # expect $value = $VALUE
             if [  -z "${1+x}" ] || [ -z "${2+x}" ] || [ -z "${3+x}" ] ; then # check if all parameters are set and not empty
             {
-                >&2 failed ${FUNCNAME[1]} requires to have 3 parameters :: ${FUNCNAME[1]} [not] to be equal to \$VALUE ::
+                >&2 echo -e "${RED} ✘ failed ${LIGHTYELLOW}${FUNCNAME[1]} requires to have 3 parameters :: ${FUNCNAME[1]} [not] to be equal to \$VALUE ::"
+                return 1
             }
             fi
             local value_one="${1}"
@@ -1256,33 +1287,36 @@ IFS=\  read value_one equality value_two<<EOF
 ${inputo}
 EOF
             value_one=$(convert_expects_internals "$(convert_null "${value_one}")")
-            (( DEBUG )) && echo "0.value_one:,,$value_one''"
+            (( DEBUG )) && echo -e "0.value_one:${RED},,${YELLOW_OVER_DARKBLUE2}$value_one${RED}''${RESET}"
             value_two=$(convert_null "${value_two}")
-            (( DEBUG )) && echo "0.value_two:,,$value_two''"
-
+            (( DEBUG )) && echo -e "0.value_two:${RED},,${DARK_BLUE_OVER_PEACH}$value_two${RED}''${RESET}"
+            (( DEBUG )) && echo -e "0.equality:${RED},,${YELLOW_OVER_DARKBLUE2}$equality${RED}''${RESET}"
             # TESTING=$(echo "${FUNCNAME[0]} that value ${statement}" | ag "${value_one}" | ag "${value_two}")
             TESTING="${FUNCNAME[0]} that value ${statement}"
-            (( DEBUG )) && echo "${FUNCNAME[0]} that value ${statement}"
-            (( DEBUG )) && echo "//"
-            (( DEBUG )) && echo "${FUNCNAME[0]} that value ${statement}"
-            (( DEBUG )) && echo "TESTING:${TESTING}"
-            (( DEBUG )) && echo "inputo:,,$inputo''"
+            (( DEBUG )) && echo -e "1.${RED}${FUNCNAME[1]} that value ${RED},,${CYAN}${statement}${RED}''${RESET}"
+            (( DEBUG )) && echo -e "1.TESTING:${LIGHTPINK_OVER_DARKBLUE}${TESTING}${RESET}"
+            (( DEBUG )) && echo -e "1.inputo:${RED},,${DARK_BLUE_OVER_PEACH}${inputo}${RED}''${RESET}"
             if [[ "${inputo}" == *"="* ]] ; then
             {
                 if [[ "${inputo}" == "=" ]] ; then
                 {
-                    passed "${TESTING}"
-                    return 0
+                    >&2 echo -e "${RED} ✘ failed ${LIGHTYELLOW}${TESTING}${YELLOW_OVER_GRAY241}"
+                    return 1
                 }
                 fi
-                value_one=$(echo "${inputo}" | cut -d= -f1 | trim)
-                (( DEBUG )) && echo "value_one:,,$value_one''"
-                value_two=$(echo "${inputo}" | cut -d= -f2 | trim)
-                (( DEBUG )) && echo "value_two:,,$value_two''"
+                value_one="${inputo%=*}"  # retain the part before the =
+                (( DEBUG )) && echo -e "=value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
+                value_two="${inputo##*=}"  # retain the part after the =
+                (( DEBUG )) && echo -e "=value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+                # value_one=$(echo -n "${inputo}" | cut -d'=' -f1 | trim)
+                # (( DEBUG )) && echo -e "=value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
+                # value_two=$(echo -n "${inputo}" | cut -d'=' -f2- | trim)
+                # (( DEBUG )) && echo -e "=value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
                 value_one=$(convert_null "${value_one}")
-                (( DEBUG )) && echo "value_one:,,$value_one''"
+                (( DEBUG )) && echo -e "=value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
                 value_two=$(convert_null "${value_two}")
-                (( DEBUG )) && echo "value_two:,,$value_two''"
+                (( DEBUG )) && echo -e "=value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+                TESTING="${RESET}${FUNCNAME[0]} that value ${YELLOW_OVER_DARKBLUE}${value_one}${RESET}${CYAN} same as ${YELLOW_OVER_GRAY241}${value_two}${RESET}"
                 if [[ "${value_one}" == "${value_two}" ]] ; then
                 {
                     passed "${TESTING}"
@@ -1295,7 +1329,7 @@ EOF
                 }
                 fi
             }
-            else
+            elif [[ "${inputo}" == *"!"* ]] ; then
             {
                 if [[ "${inputo}" == "!" ]] ; then
                 {
@@ -1303,14 +1337,16 @@ EOF
                     return 1
                 }
                 fi
-                value_one=$(echo "${inputo}" | cut -d! -f1 | trim)
-                (( DEBUG )) && echo "value_one:,,$value_one''"
-                value_two=$(echo "${inputo}" | cut -d! -f2 | trim)
-                (( DEBUG )) && echo "value_two:,,$value_two''"
+                value_one="${inputo%!*}"  # retain the part before the !
+                (( DEBUG )) && echo -e "!value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
+                value_two="${inputo##*!}"  # retain the part after the !
+                (( DEBUG )) && echo -e "!value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+
                 value_one=$(convert_null "${value_one}")
-                (( DEBUG )) && echo "value_one:,,$value_one''"
+                (( DEBUG )) && echo -e "!value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
                 value_two=$(convert_null "${value_two}")
-                (( DEBUG )) && echo "value_two:,,$value_two''"
+                (( DEBUG )) && echo -e "!value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+                TESTING="${FUNCNAME[0]} that value ${YELLOW_OVER_DARKBLUE}${value_one}${RESET}${CYAN} not equal ${YELLOW_OVER_GRAY241}${value_two}${RESET}"
                 if [[ "${value_one}" != "${value_two}" ]] ; then
                 {
                     passed "${TESTING}"
@@ -1323,7 +1359,44 @@ EOF
                 }
                 fi
             }
+            elif [[ "${inputo}" == *"~"* ]] ; then
+            {
+                if [[ "${inputo}" == "~" ]] ; then
+                {
+                    >&2 echo -e "${RED} ✘ failed ${LIGHTYELLOW}${TESTING}${CYAN}"
+                    return 1
+                }
+                fi
+                value_one="${inputo%~*}"  # retain the part before the ~
+                (( DEBUG )) && echo -e "~value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
+                value_two="${inputo##*~}"  # retain the part after the ~
+                (( DEBUG )) && echo -e "~value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+
+                value_one=$(convert_null "${value_one}")
+                (( DEBUG )) && echo -e "~value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
+                value_two=$(convert_null "${value_two}")
+                (( DEBUG )) && echo -e "~value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+
+                TESTING="${FUNCNAME[0]} that value ${YELLOW_OVER_DARKBLUE}${value_one}${RESET}${CYAN} to contain ${YELLOW_OVER_GRAY241}${value_two}${RESET}"
+                if [[ "${value_one}" == *"${value_two}"* ]] ; then
+                {
+                    passed "${TESTING}"
+                    return 0
+                }
+                else
+                {
+                    >&2 echo -e "${RED} ✘ failed ${LIGHTYELLOW}${TESTING}${CYAN}"
+                    return 1
+                }
+                fi            
+            } 
+            else 
+            {
+                >&2 echo -e "${RED} ✘ failed. Case 1. Do not know how to do: ${LIGHTYELLOW}${TESTING}${CYAN}"
+                return 1
+            }
             fi
+            >&2 echo -e "${RED} ✘ failed. Case 2. Do not know how to do: ${LIGHTYELLOW}${TESTING}${CYAN}"
             return 1
         } # end expect
 
