added package installer and git clone function

diff --git a/struct_testing b/struct_testing
--- a/struct_testing
+++ b/struct_testing
@@ -6247,7 +6247,8 @@ function raise_to_sudo_and_user_home() {
       fi
     fi
     [[ -z "${bootbasicsource}" ]] && echo -e "\n \n  ERROR! Loading execute_boot_basic.sh  bootbasicsource did not download or is empty " && exit 1
-    local _temp_dir="$(mktemp -d 2>/dev/null || mktemp -d -t 'execute_boot_basic_source')"
+    local _temp_dir=""
+		_temp_dir="$(mktemp -d 2>/dev/null || mktemp -d -t 'execute_boot_basic_source')"
     echo "${bootbasicsource}">"${_temp_dir}/execute_boot_basic_source"
     if (( _DEBUG )) ; then
       echo "$0 execute_command_intuivo_cli/struct_testing load_execute_boot_basic_with_sudo() Temp execute_boot_basic.sh location ${_temp_dir}/execute_boot_basic_source"
@@ -6356,7 +6357,9 @@ function enforce_web_is_reachable(){
   # enforce_web_is_reachable  "cms.artbox.one"
   #
   local _url="${1}"
-  local _domain=$(extract_domainname "${_url}")
+	local -i _err=0
+  local _domain=""
+	_domain=$(extract_domainname "${_url}")
   enforce_variable_with_value _domain "${_domain}"
   echo "  Checking for connection to ${_domain}"
   local msg
@@ -6511,6 +6514,114 @@ function _remove_package() {
 } # end _remove_package
 
 
+function _package_list_installer() {
+  #
+  # Sample use
+  # trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
+  local package
+	local packages=""
+	packages="${*-}"
+  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _package_list_installer " && echo -e "${RESET}" && return 0' ERR
+
+  if ! install_requirements "linux" "${packages}" ; then
+  {
+    warning "installing requirements. ${CYAN} attempting to install one by one"
+    while read -r package; do
+    {
+      [[ -z "${package}" ]] && continue
+      if ! install_requirements "linux" "${package}" ; then
+      {
+        _err=$?
+        if [ ${_err} -gt 0 ] ; then
+        {
+          echo -e "${RED}"
+          echo failed to install requirements "${package}"
+          echo -e "${RESET}"
+        }
+        fi
+      }
+      fi
+    }
+    done <<< "${packages}"
+  }
+  fi
+} # end _package_list_installer
+
+function _git_clone() {
+  #
+  # Sample use
+  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
+  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO  _git_clone " && echo -e "${RESET}" && return 0' ERR
+  local _source="${1}"
+  local _target="${2}"
+  Checking "${SUDO_USER}" "${_target}"
+  local _cwd=""
+	_cwd="$(pwd)"
+  Checking "_cwd:${_cwd}"
+  if  it_exists_with_spaces "${_target}" ; then # && it_exists_with_spaces "${_target}/.git" ; then
+  {
+    if it_exists_with_spaces "${_target}/.git" ; then
+    {
+      cd "${_target}" || exit 1
+      if git branch --set-upstream-to=origin/master master ; then
+      {
+        warning "Could not do git branch --set-upstream-to=origin/master master"
+      }
+      fi
+      if git branch --set-upstream-to=origin/main main ; then
+      {
+        warning "Could not do git branch --set-upstream-to=origin/main main"
+      }
+      fi
+      if git config pull.rebase false ; then
+      {
+        warning "Could not git config pull.rebase false"
+      }
+      fi
+      if git fetch  ; then
+      {
+        warning Could not git fetch
+      }
+      fi
+      if git pull  ; then
+      {
+        warning Could not git pull
+      }
+      fi
+    }
+    fi
+  }
+  else
+  {
+    if git clone "${_source}" "${_target}"  ; then
+    {
+      warning Could not git clone "${_source}" "${_target}"
+    }
+    else
+		{
+      if git branch --set-upstream-to=origin/master master ; then
+      {
+        warning "Could not do git branch --set-upstream-to=origin/master master"
+      }
+      fi
+      if git branch --set-upstream-to=origin/main main ; then
+      {
+        warning "Could not do git branch --set-upstream-to=origin/main main"
+      }
+      fi
+      if git config pull.rebase false ; then
+      {
+        warning "Could not git config pull.rebase false"
+      }
+      fi
+		}
+    fi
+  }
+  fi
+  chown -R "${SUDO_USER}" "${_target}"
+  cd "${_cwd}" || exit 1
+} # end _git_clone
+
 function _remove_package_if_it_exists() {
   #
   # Sample use
@@ -6618,13 +6729,13 @@ function _process_dmgs_dmg_or_zip() {
     echo " "
     if ! it_exists "/Volumes/${UNZIPDIR}" ; then
     {
-      warning ${APPDIR} failed to check mount  "/Volumes/${UNZIPDIR}"
+      warning "${APPDIR} failed to check mount  /Volumes/${UNZIPDIR}"
       return 1
     }
     fi
     if ! it_exists  "/Volumes/${UNZIPDIR}/${APPDIR}" ; then
     {
-      warning ${APPDIR} failed to check mount  "/Volumes/${UNZIPDIR}/${APPDIR}"
+      warning "${APPDIR} failed to check mount  /Volumes/${UNZIPDIR}/${APPDIR}"
       return 1
     }
     fi
@@ -6672,7 +6783,8 @@ function _install_dmgs_dmg__64() {
   # _install_dmgs_dmg__64 "${target_name}" "${target_app}" "${target_url}"
   #
   local CODENAME="${1}"
-  local extension="$(echo "${CODENAME}" | rev | cut -d'.' -f 1 | rev)"
+  local extension=""
+	extension="$(echo "${CODENAME}" | rev | cut -d'.' -f 1 | rev)"
   local APPDIR="${2}"
   local TARGET_URL="${3}"
   # CODENAME="$(basename "${TARGET_URL}" )"
@@ -6683,7 +6795,8 @@ function _install_dmgs_dmg__64() {
   # local UNZIPDIR="$(echo -en "${CODENAME}" | sed 's/.dmg//g'| sed 's/-//g')"
   # local UNZIPDIR="$(echo -en "${APPDIR}" | sed 's/.app//g')"
   # echo "$(pwd)"
-  local UNZIPDIR="$(dirname  "${APPDIR}")"
+  local UNZIPDIR=""
+	UNZIPDIR="$(dirname  "${APPDIR}")"
   local APPDIR="${APPDIR##*/}"    # same as  $(basename "${APPDIR}")
   #local APPDIR=$(basename "${APPDIR}")
   # local APPDIR="$(echo -en "${CODENAME}" | sed 's/.dmg//g'| sed 's/-//g').app"
