moved handling error in requiring function

diff --git a/struct_testing b/struct_testing
--- a/struct_testing
+++ b/struct_testing
@@ -1075,9 +1075,35 @@ CERO="\033[01;0m"
 
             # Check Requirements OS Ubuntu 14.04 REF: https://wiki.postgresql.org/wiki/Compile_and_Install_from_source_code#Ubuntu
             [[ ! -z "${missing}" ]] && echo -e " ${CYAN} Installing missing packages: ${YELLOW} ${missing} ${RESET} ."
-            [[ ! -z "${missing}" ]] && local install_result=$(sudo apt-get install ${missing} -yfq   2>&1) # capture all input and output
+            local err_buff=0
+
+            if [[ ! -z "${missing}" ]] ; then
+            {
+                local install_result=$(sudo apt-get install ${missing} -yfq   2>&1) # capture all input and output
+                err_buff=$?
+            }
+            fi
             echo $install_result;
-            [[ ! -z "${install_result}" ]] && handle_error "${install_result}"
+            if [[ ! -z "${install_result}" ]] ; then #  && handle_error "${install_result}"
+            {
+                local error_happened=""
+                [[ "${PROCESSOR_ERROR}" == *"MAC"* ]] && [ $err_buff != 0 ] && error_happened="1"
+                [[ "${PROCESSOR_ERROR}" == *"INTEL"* ]] && (( $err_buff != 0 )) && error_happened="1"
+                if [ "${error_happened}" ]  ||  ( has_error_keyword "${install_result}" ) ; then
+                {
+                  echo -e "${PURPLE_BLUE} action ${RED}failed ${YELLOW226}!!!  ${RESET}"
+                  [[ "${install_result}" == *"Could not resolve"* ]] && echo -e "${BRIGHT_BLUE87} It appears YOU HAVE ${YELLOW226}NO INTERNET CONNECTION \o_0/ ${RESET}"
+                  [[ "${install_result}" == *"Repository not found"* ]] && echo -e "${BRIGHT_BLUE87} It appears YOU HAVE ${YELLOW226}NO ACCESS TO THIS FOR YOU ${RED} ${GIT_USER_NAME} ${RESET}"
+                  [[ "${install_result}" == *"Could not read from"* ]] && echo -e "${BRIGHT_BLUE87} It appears it exists but you are ${RED}NOT ${YELLOW226} ALLOWED ${RED} ${GIT_USER_NAME} ${YELLOW226}!!! ${RESET}"
+                  RED="\\033[01;31m"
+                  CYAN="\\033[01;36m"
+                  echo -e "${install_result}" | sed "s/\(FAILED\|failed\|Failed\|ERROR\|Error\|error\|cannot\|continue\|logged\|inspection\|not\|exit\|more\|details\)/${RED}\1${CYAN}/g"
+                  failed "${RESET} \n .... \n ... ${install_result} \n ... \n ..."
+                }
+                fi
+
+            }
+            fi
         }
         # end install_apt_get_requirements
 
