added refactor functions for struct testing

diff --git a/struct_testing b/struct_testing
--- a/struct_testing
+++ b/struct_testing
@@ -2477,6 +2477,501 @@ enter_last_only_removed() {
             [ -f "/home/${USER_TO_INSTALL}/${target}" ] &&  chown -R "${USER_TO_INSTALL}":"${USER_TO_INSTALL}" "/root/${target}"
         }
         alias move_file_out_root_to_user_and_link_it_back=move_to_user_file_and_soft_link_root_to_it
+
+##############           ##############             ####      ####           ##############               ############             ##############             ####      ####          
+##############           ##############             ####      ####           ##############               ############             ##############             ####      ####          
+    ######               ####        ####             ####  ####             ####        ####           ####        ####           ####        ####             ####  ####            
+    ######               ####        ####             ####  ####             ####        ####           ####        ####           ####        ####             ####  ####            
+    ######               ####        ####               ######               ##############             ####        ####           ####        ####               ######              
+    ######               ####        ####               ######               ##############             ####        ####           ####        ####               ######              
+    ######               ##############                 ######               ####        ####           ####        ####           ####        ####               ######              
+    ######               ##############                 ######               ####        ####           ####        ####           ####        ####               ######              
+    ######               ####      ####                 ######               ####        ####           ####        ####           ####        ####               ######              
+    ######               ####      ####                 ######               ####        ####           ####        ####           ####        ####               ######              
+    ######               ####        ####               ######               ##############               ############             ##############                 ######              
+    ######               ####        ####               ######               ##############               ############             ##############                 ######         
+
+
+# SUDO_USER only exists during execution of sudo
+# REF: https://stackoverflow.com/questions/7358611/get-users-home-directory-when-they-run-a-script-as-root
+# Global:
+# THISSCRIPTNAME=`basename "$0"`
+
+function execute_as_sudo(){
+    # Sample use:
+    # being of script add 
+    # THISSCRIPTNAME=`basename "$0"`
+    # ...
+    # execute_as_sudo
+    # USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
+    # passed Caller user identified:$USER_HOME
+    # 
+  if [ -z $SUDO_USER ] ; then
+    if [[ -z "$THISSCRIPTNAME" ]] ; then
+    {
+        echo "error You need to add THISSCRIPTNAME vairable like this:" 
+        echo "     THISSCRIPTNAME=\`basename \"\$0\"\`"
+    }
+    else 
+    {
+        if [ -e "./$THISSCRIPTNAME" ] ; then
+        {       
+        sudo "./$THISSCRIPTNAME"
+        }
+        elif ( command -v type "$THISSCRIPTNAME" >/dev/null 2>&1 );  then
+        {
+        echo "sudo sudo sudo "
+        sudo "$THISSCRIPTNAME"
+        }
+        else
+        {
+        echo -e "\033[05;7m*** Failed to find script to recall it as sudo ...\033[0m"
+        exit 1
+        }
+        fi
+    }
+    fi
+    wait
+    exit 0
+  fi
+  # REF: http://superuser.com/questions/93385/run-part-of-a-bash-script-as-a-different-user
+  # REF: http://superuser.com/questions/195781/sudo-is-there-a-command-to-check-if-i-have-sudo-and-or-how-much-time-is-left
+  local CAN_I_RUN_SUDO=$(sudo -n uptime 2>&1|grep "load"|wc -l)
+  if [ ${CAN_I_RUN_SUDO} -gt 0 ]; then
+    echo -e "\033[01;7m*** Installing as sudo...\033[0m"
+  else
+    echo "Needs to run as sudo ... ${0}"
+  fi
+} # end execute_as_sudo
+
+function _download() {
+  #  url  https://www.scootersoftware.com/master-pdf-editor-3133_amd64.deb
+  _trap_try_start
+  local target_url="${1}"
+  if [ -z "${target_url}" ] ; then  # if empty
+  {
+    failed Could not load target_url string or it was empty. Expected one Parameter URL
+  }
+  fi
+  _trap_catch_check
+  # wget --directory-prefix="${USER_HOME}/Downloads/" --quiet --no-check-certificate "${target_url}" 2>/dev/null
+  echo -e "\033[01;7m*** Downloading file to temp location...\033[0m"
+  if ( command -v type wget >/dev/null 2>&1; ) ; then
+    # # REF: about :> http://unix.stackexchange.com/questions/37507/what-does-do-here
+    _trap_try_start
+    :> wgetrc   # here :> equals to Equivalent to the following: cat /dev/null > wgetrc which Nulls out the file called "wgetrc" in the current directory. As in creates an empty file "wgetrc" if one doesn't exist or overwrites one with nothing if it does.
+    _trap_catch_check
+    file_exists_with_spaces wgetrc
+    _trap_try_start
+    echo "noclobber=off" >> wgetrc
+    _trap_catch_check
+    echo "dir_prefix=." >> wgetrc
+    echo "dirstruct=off" >> wgetrc
+    echo "verbose=off" >> wgetrc    # NOTE Can't be verbose and quiet at the same time.--quiet
+    echo "progress=bar:default" >> wgetrc
+    echo "tries=3" >> wgetrc
+    # _trap_try_start # _trap_catch_check
+    # WGETRC=wgetrc wget --directory-prefix="${USER_HOME}/Downloads/" --quiet --no-check-certificate "${target_url}" 2>/dev/null
+    #  _trap_catch_check
+    # WGETRC=wgetrc wget --quiet --no-check-certificate "${target_url}" 2>/dev/null   # suppress only wget download messages, but keep wget output for variable
+    _try "WGETRC=wgetrc wget --directory-prefix=\"${USER_HOME}/Downloads/\" --quiet --no-check-certificate \"${target_url}\"" # 2>/dev/null"
+    echo -e "\033[7m*** Download Wget executed completed.\033[0m"
+    rm -f wgetrc
+    file_does_not_exist_with_spaces wgetrc
+  elif ( command -v type curl >/dev/null 2>&1; ); then
+    curl -O "${target_url}" 2>/dev/null   # suppress only wget download messages, but keep wget output for variable
+    _assure_success
+  else
+    failed "I cannot find wget or curl programs to perform a download action! ${target_url}"
+  fi
+}
+
+
+function _assure_success() {
+  if [ $? != 0 ] ; then
+    echo -e "\033[38;5;1m Something went wrong \033[0m"
+    exit 1
+  fi
+  wait
+}
+
+function _trap_try_start() {
+  trap _term SIGTERM
+}
+
+function _trap_catch_check() {
+  declare -i ret=$?
+  local child
+  if [ $ret -gt 0 ] ; then
+  {
+    child=$!
+    wait $child
+    warning "${YELLOW}Error SIGNAL_RETURN(${RED}${ret}${YELLOW}) executing: \n${action}"
+    return 1 # non zero is error
+  }
+  fi
+  return 0
+}
+
+function _action_runner() {
+  local action	
+  while read -r action ; do
+  {
+    if [[ ! -z "${action}" ]] ; then # if not empty
+    {
+      _trap_try_start
+      echo "${action}"
+      "${action}"
+      _trap_catch_check
+    }
+    fi
+  }
+  done <<< "${@}"
+} # end _action_runner
+
+function _try_runner() {
+  local body=$(_function_body "#{1}")
+  function_exists "${1}"
+  while read -r action ; do
+  {
+    if [[ ! -z "${action}" ]] ; then # if not empty
+    {
+      _trap_try_start
+      echo "${action}"
+      "${action}"
+      _trap_catch_check
+    }
+    fi
+  }
+  done <<< "${body}"
+} # end _try_runner
+
+function _function_body() {
+  local functionname="${1}"
+  # function_exists "${functionname}"
+  # ensure head or Cancel. Missing head command
+  # ensure tail or Cancel. Missing tail command
+  # ensure declare or Cancel. Missing declare command
+  # ensure wc or Cancel. Missing declare command
+  local functioncomplete=$(declare -f "${functionname}")
+  # echo complete:"${functioncomplete}"
+  local functionbody=$(echo "${functioncomplete}" | cuet "${functionname} ()")
+  # echo body:"${functionbody}"
+  local functionlength=$(echo "${functionbody}" | wc -l)
+  # echo length:${functionlength}
+  # echo less:${functionlengthless}
+  (( functionlength-- ))
+  # echo lenght:${functionlength}
+  functionbody=$(echo "${functionbody}" | head -${functionlength} )
+  # echo body:"${functionbody}"
+  (( functionlength-- ))
+  # echo length:${functionlength}
+  functionbody=$(echo "${functionbody}" | tail -${functionlength} )
+  # echo body:"${functionbody}"
+  echo "${functionbody}"
+}
+
+function _try_body() {
+  local body=$(_function_body "${1}")
+  _trap_try_start
+  echo "${body}"
+  "${body}"
+  _trap_catch_check
+}
+
+function _try() {
+  local body="${@}"
+  _trap_try_start
+  echo -e "\033[01;7m***${body}\033[0m***"
+  local msg="${body}"
+  declare -i ret=_trap_catch_check
+  echo "${msg}"
+  unset body
+  unset msg
+  if [ $ret -gt 0 ] ; then
+    unset ret
+    return 1
+  else
+    unset ret
+    return 0
+  fi
+}
+
+
+function function_is_defined_with_spaces() {
+		    # Sample usage
+		    #
+		    #          if  ! function_is_defined_with_spaces "/home/vagrant/.zshrc" ; then    is like is NOT installed
+		    #          if  function_is_defined_with_spaces "/root/.zshrc ; then      it makes more sense to make it this way
+		    #
+            local ONE_FUNCTION FUNCTIONS="${@}"
+            if [ ! -z "${FILES-x}" ] ; then # if its set and not empty
+            {
+                while read -r ONE_FUNCTION; do
+                # if not empty
+                if [ ! -z "${ONE_FUNCTION}" ] ; then
+                    if [ -n "$(LC_ALL=C type -t "${ONE_FUNCTION}")" ] && [ "$(LC_ALL=C type -t "${ONE_FUNCTION}")" = function ]; then
+                    {
+                        return 0 # function exists
+                    }
+                    fi
+                fi
+                done <<< "${FUNCTIONS}"
+                return 1 # function does not exists
+            }
+            fi
+            unset ONE_FUNCTION
+            unset FUNCTIONS
+            unset TESTING
+} # end function_is_defined_with_spaces
+
+function function_is_defined() {
+	    # Sample usage
+	    #
+	    #          if  ! function_is_defined determine_os_and_fire_action ; then    is like is NOT installed
+	    #          if  function_is_defined "$FUNCTION_TO_CALL" ; then      it makes more sense to make it this way
+            #
+            local ONE_FUNCTION FUNCTIONS="${@}"
+            if [ ! -z "${FILES-x}" ] ; then # if its set and not empty
+            {
+                FUNCTIONS=$(switch_spaces_to_newlines <<< "${@}")
+                while read -r ONE_FUNCTION; do
+                # if not empty
+                if [ ! -z "${ONE_FUNCTION}" ] ; then
+	            if [ -n "$(LC_ALL=C type -t "${ONE_FUNCTION}")" ] && [ "$(LC_ALL=C type -t "${ONE_FUNCTION}")" = function ]; then 
+                    {
+                        return 0 # function exists
+                    }
+                    fi
+                fi
+                done <<< "${FUNCTIONS}"
+                return 1 # function does not exists
+            }
+            fi
+            unset ONE_FUNCTION 
+            unset FUNCTIONS
+            unset TESTING
+
+} # end function_is_defined
+
+function function_exists() {
+            # Sample usage
+            #
+            #     function_exists determine_os_and_fire_action
+            #     function_exists  "$FUNCTION_TO_CALL"
+            #     function_exists "Function1
+	    #                      Function2
+            #                      Function2"	    
+            #
+            local TESTING ONE_FUNCTION FUNCTIONS="${@}"
+            if [ ! -z "${FUNTIONS-x}" ] ; then # if its set and not empty
+            {
+                FUNCTIONS=$(switch_spaces_to_newlines <<< "${@}")
+                while read -r ONE_FUNCTION; do
+                if [ ! -z "${ONE_FUNCTION}" ] ; then # if not empty
+                    TESTING="that function ${CYAN}${ONE_FUNCTION}${LIGHTYELLOW} exists"
+                    if function_is_defined "${ONE_FUNCTION}" ; then
+                    {
+                        passed "${TESTING}"
+                    }
+                    else
+                    {
+                        failed "${TESTING}"
+                    }
+                    fi
+                fi
+                done <<< "${FUNCTIONS}"
+            }
+            fi
+	    unset ONE_FUNCTION 
+	    unset FUNCTIONS
+	    unset TESTING
+
+} # end function_exists
+
+# function_exists ls
+# build_table_from_installed_components $USER
+# build_table_from_installed_components $SUDO_USER
+
+function function_exists_with_spaces() {
+            # Sample usage
+            #
+            #     function_exists_with_spaces determine_os_and_fire_action
+            #     function_exists_with_spaces  "$FUNCTION_TO_CALL"
+	    #     function_exists_with_spaces "Function1
+            #                      Function2
+            #                      Function2"       
+            #
+            local TESTING ONE_FUNCTION FUNCTIONS="${@}"
+            if [ ! -z "${FUNTIONS-x}" ] ; then # if its set and not empty
+            {
+                while read -r ONE_FUNCTION; do
+                if [ ! -z "${ONE_FUNCTION}" ] ; then # if not empty
+                    TESTING="that function ${CYAN}${ONE_FUNCTION}${LIGHTYELLOW} exists"
+                    if function_is_defined_with_spaces "${ONE_FUNCTION}" ; then
+                    {
+                        passed "${TESTING}"
+                    }
+                    else
+                    {
+                        failed "${TESTING}"
+                    }
+                    fi
+                fi
+			done <<< "${FUNCTIONS}"
+            }
+            fi
+            unset ONE_FUNCTION 
+            unset FUNCTIONS
+            unset TESTING
+} # end function_exists_with_spaces
+
+function determine_os_and_fire_action() {
+  # Interface
+  local FUNCTION_TO_CALL=""
+  local PARAMETERS=""  
+  # Check operating systems
+  if [[ "$(uname)" == "Darwin" ]] ; then
+      # Do something under Mac OS X platform
+      if [[ "$(uname -m)" == "x86_64" ]] ; then
+      { 
+	     FUNCTION_TO_CALL='_darwin__64'
+	     PARAMETERS="$@"
+      }
+      elif [[ "$(uname -m)" == "i686"   ]] ; then 
+      {
+	     FUNCTION_TO_CALL='_darwin__32'
+	     PARAMETERS="$@"
+      }
+      fi
+  elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
+    # Do something under GNU/Linux platform
+    # Determine OS platform
+    local UNAME=$(uname | tr "[:upper:]" "[:lower:]")
+    local DISTRO=""
+    local ID=""
+    local VERSION_ID=""
+    # If Linux, try to determine specific distribution
+    if [ "$UNAME" == "linux" ]; then
+        # If available, use LSB to identify distribution
+        if [ -f /etc/lsb-release -o -d /etc/lsb-release.d ]; then
+	    if ( command -v type lsb_release >/dev/null 2>&1; ); then
+            {
+              DISTRO=$(lsb_release -i | cut -d: -f2 | sed s/'^\t'//)
+            }
+            else
+            {
+              DISTRO=$(ls -d /etc/[A-Za-z]*[_-][rv]e[lr]* | grep -v "lsb" | cut -d'/' -f3 | cut -d'-' -f1 | cut -d'_' -f1)
+	    }
+            fi
+        # Otherwise, use release info file
+        else
+            DISTRO=$(ls -d /etc/[A-Za-z]*[_-][rv]e[lr]* | grep -v "lsb" | cut -d'/' -f3 | cut -d'-' -f1 | cut -d'_' -f1)
+        fi
+    fi
+    if [[ -z "$DISTRO" ]]; then  # if empty
+    {
+      # If available, use /etc/os-release to identify distribution
+        if [ -f /etc/os-release ]; then
+        {
+		source /etc/os-release
+                # file_exists "/etc/os-release"
+                _assure_success
+                # source /etc/os-release
+                # $ echo $ID
+                # fedora
+                # $ echo $VERSION_ID
+                # 17
+                # $ echo $VERSION
+                # 17 (Beefy Miracle)
+                DISTRO=$ID
+	}
+        fi
+    }
+    fi
+    if [[ -z "$DISTRO" ]]; then  # if empty
+    {
+        failed to determine DISTRO for this linux. uname -a, cat /etc/os-release, lsb_release -i
+    }
+    fi
+
+    if [[ "$DISTRO" == *"edora"* ]]; then
+    {
+        if [[ "$(uname -i)" == "x86_64" ]] ; then
+        {
+	  FUNCTION_TO_CALL='_fedora__64'
+	  PARAMETERS="$@"
+        }
+        elif [[ "$(uname -i)" == "i686"   ]] ; then
+	{
+	  FUNCTION_TO_CALL='_fedora__32'
+          PARAMETERS="$@"
+        }
+	fi
+    }
+    elif [[ "$DISTRO" == *"untu"* ]]; then
+    {
+        # ubuntu lsb_release -i | sed 's/Distributor\ ID://g' = \tUbuntu\n
+        if [[ "$(uname -i)" == "x86_64" ]] ; then 
+	{ 
+	  FUNCTION_TO_CALL='_ubuntu__64'
+	  PARAMETERS="$@"
+	}
+        elif [[ "$(uname -i)" == "i686"   ]] ; then 
+	{ 
+	  FUNCTION_TO_CALL='_ubuntu__32'
+	  PARAMETERS="$@"
+	}
+	fi
+    }
+    fi
+    # For everything else (or if above failed), just use generic identifier
+    unset UNAME
+    unset DISTRO
+    unset ID
+
+  elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then
+    # Do something under Windows NT platform
+    if [[ "$(uname -i)" == "x86_64" ]] ; then
+    { 
+      FUNCTION_TO_CALL='_mingw__64'
+      PARAMETERS="$*"
+    }
+    elif [[ "$(uname -i)" == "i686"   ]] ; then
+    { 
+      FUNCTION_TO_CALL='_mingw__32'
+      PARAMETERS="$*"
+    }
+    fi
+    # nothing here
+  else 
+    failed system not recognized
+  fi
+  if [[ -z "$FUNCTION_TO_CALL" ]]; then  # if empty
+  {
+     failed to determine FUNCTION_TO_CALL for this OS. uname -a, cat /etc/os-release, lsb_release -i
+  }
+  else
+  {
+        if function_is_defined "${FUNCTION_TO_CALL}" ; then
+        {
+           "${FUNCTION_TO_CALL}"
+	   _assure_success
+        }
+        else
+        {
+	   failed to find function for this OS or DISTRO:  "${FUNCTION_TO_CALL}"
+	   _assure_success
+        }
+	fi
+
+  }
+  fi
+  _assure_success
+  unset FUNCTION_TO_CALL
+  unset PARAMETERS
+} # end determine_os_and_fire_action
+
     #[ ! -z "$0" ] && [ -e "$0" ] && THISSCRIPTNAME=`basename "$0"`
 
     # TRAP
