fixed DEBUG missing var undeclared _DEBUG more

diff --git a/struct_testing b/struct_testing
--- a/struct_testing
+++ b/struct_testing
@@ -351,7 +351,7 @@ CERO="\033[01;0m"
           # Sample use
           # enforce_parameter_with_options 2 PLATFORM "${PLATFORM}" "mac windows linux"
           # Tests for the function
-          # DEBUG=1
+          # _DEBUG=1
 					local -i _DEBUG=${DEBUG:-0}
           local TESTING="enforce_parameter_with_options function ${FUNCNAME[1]} param at position ${RESET}<${YELLOW_OVER_DARKBLUE}${1}${RESET}${LIGHTYELLOW}> alias for <${CYAN}${2}${LIGHTYELLOW}> to have one of these values ${RESET}<${YELLOW_OVER_DARKBLUE}${4}${RESET}>"
           (( _DEBUG )) && echo -e "${FUNCNAME[0]}"
@@ -374,10 +374,10 @@ CERO="\033[01;0m"
             # local -i found=0
             while read -r one ; do
             {
-              (( DEBUG )) && echo "checking value ${FUNCNAME[1]} ${3}  ${one} "
+              (( _DEBUG )) && echo "checking value ${FUNCNAME[1]} ${3}  ${one} "
               if [[ -n "${one}" ]]  ; then
               {
-                (( DEBUG )) && echo "one is "
+                (( _DEBUG )) && echo "one is "
                 if [[ "${3}" == "${one}" ]] ; then
                 {
                   # found=1
@@ -389,7 +389,7 @@ CERO="\033[01;0m"
             }
             done <<< "$(switch_spaces_to_newlines <<< "${@}")"
             # done <<< "${4}"
-            (( DEBUG )) && echo -e "${LIGHTGREEN} ✔ ${LIGHTYELLOW} ${TESTING} has passed "
+            (( _DEBUG )) && echo -e "${LIGHTGREEN} ✔ ${LIGHTYELLOW} ${TESTING} has passed "
             #(( found )) &&
             return 0
           }
@@ -431,7 +431,7 @@ CERO="\033[01;0m"
           (( _seemsempty_ )) && exit 1
           if ( typeset -p "${2}"  &>/dev/null ) &&  [ -n "${3+x}" ] ; then
           {
-              (( DEBUG )) && echo -e "${LIGHTGREEN} ✔ ${LIGHTYELLOW} ${TESTING} has passed "
+              (( _DEBUG )) && echo -e "${LIGHTGREEN} ✔ ${LIGHTYELLOW} ${TESTING} has passed "
               return 0
           }
           else
@@ -466,7 +466,7 @@ CERO="\033[01;0m"
 
         function enforce_variable_with_value(){
           # Sample use
-          # DEBUG=1
+          # _DEBUG=1
           # enforce_variable_with_value HOME $HOME
           # enforce_variable_with_value USER_HOME $USER_HOME
           # enforce_variable_with_value SUDO_USER $SUDO_USER
@@ -1048,7 +1048,7 @@ CERO="\033[01;0m"
             {
                 while read -r ONE_FILE; do
                 # if not empty
-                # DEBUG echo -e "${BASH_SOURCE[0]} ->\n  .. ${FUNCNAME[0]}():${ONE_FILE}"
+                # _DEBUG echo -e "${BASH_SOURCE[0]} ->\n  .. ${FUNCNAME[0]}():${ONE_FILE}"
                 if [ -n "${ONE_FILE}" ] ; then
                 {
                     # AS a NOTE ~/  <-- will fail always
@@ -1081,7 +1081,7 @@ CERO="\033[01;0m"
             {
                 while read -r ONE_FILE; do
                 # if not empty
-                # DEBUG echo -e "${BASH_SOURCE[0]} ->\n  .. ${FUNCNAME[0]}():${ONE_FILE}"
+                # _DEBUG echo -e "${BASH_SOURCE[0]} ->\n  .. ${FUNCNAME[0]}():${ONE_FILE}"
                 if [ -n "${ONE_FILE}" ] ; then
                     # AS a NOTE ~/  <-- will fail always
                     # SO ~/.zshrc <-- will fail always
@@ -1186,13 +1186,13 @@ CERO="\033[01;0m"
             local ONE_FILE=""
             local TESTING=""
             local FILES="${*}"
-            # DEBUG echo -e "${BASH_SOURCE[0]} ->\n  .. ${FUNCNAME[0]}():$FILES"
+            # _DEBUG echo -e "${BASH_SOURCE[0]} ->\n  .. ${FUNCNAME[0]}():$FILES"
             if [ -n "${FILES-x}" ] ; then # if its set and not empty
             {
                 while read -r ONE_FILE; do
                 if [ -n "${ONE_FILE}" ] ; then # if not empty
                     TESTING="that file „${CYAN}${ONE_FILE}${LIGHTYELLOW}” exists"
-                    # DEBUG echo -e "${BASH_SOURCE[0]} ->\n  .. ${FUNCNAME[0]}():$ONE_FILE"
+                    # _DEBUG echo -e "${BASH_SOURCE[0]} ->\n  .. ${FUNCNAME[0]}():$ONE_FILE"
                     if it_exists_with_spaces "${ONE_FILE}" ; then
                     {
                         passed "${TESTING}"
@@ -1535,7 +1535,8 @@ CERO="\033[01;0m"
             #
             #     check_equality $(cat ~/.pyenv/version)="2.7.11"
             #
-            (( DEBUG )) && echo "FUNCNAME[0]: <${FUNCNAME[0]}>"
+            local -i _DEBUG=${DEBUG:-0}
+						(( _DEBUG )) && echo "FUNCNAME[0]: <${FUNCNAME[0]}>"
             local -a ARGS="${@}"
             local LEFT_VALUE=""
             local RIGHT_VALUE=""
@@ -1548,9 +1549,9 @@ CERO="\033[01;0m"
                     if [ -n "${ONE_EQUALITY_ORDER}" ] ; then
                     {
                         LEFT_VALUE=$(echo """${ONE_EQUALITY_ORDER}""" | cut -d'=' -f1 | trim)
-                        (( DEBUG )) && echo "-left: <$LEFT_VALUE>"
+                        (( _DEBUG )) && echo "-left: <$LEFT_VALUE>"
                         RIGHT_VALUE=$(echo """${ONE_EQUALITY_ORDER}""" | cut -d'=' -f2 | trim)
-                        (( DEBUG )) && echo "right: <$RIGHT_VALUE>"
+                        (( _DEBUG )) && echo "right: <$RIGHT_VALUE>"
 
                         local TESTING="that value left value: ${CYAN}${LEFT_VALUE}${LIGHTYELLOW} exists"
                         if [[ -z "${LEFT_VALUE-x}" ]] ; then
@@ -1781,7 +1782,7 @@ function _run_command(){
   #    local changelogfile="logs/__run_command.log"
   #    echo "$(date +%Y%m%d%H%M)">"${changelogfile}"
   #     exec 3>&1 1>>${changelogfile} 2>&1  # How to write output to both console and file REF: https://stackoverflow.com/questions/18460186/writing-outputs-to-log-file-and-console
-
+  local -i _DEBUG=${DEBUG:-0}
   local _node_run_command=''
   echo -e "${PURPLE} struct_testing:$LINENO _run_command ❓ ${CYAN}${*}"
   # shellcheck disable=SC2031
@@ -1796,7 +1797,7 @@ function _run_command(){
     _err=$?
   }
   fi
-  (( DEBUG )) && echo "__run_command: ${_node_run_command} --- _err: ${_err}"
+  (( _DEBUG )) && echo "__run_command: ${_node_run_command} --- _err: ${_err}"
   if [ $_err -ne 0 ] ;  then
   {
     >&2 echo -e "${RED} ✘ ${YELLOW_OVER_DARKBLUE}${*}${RESET} Err:$_err Output: $_node_run_command"
@@ -1880,7 +1881,8 @@ function _run_command(){
             statement="""${@}"""
                 #| sed 's/'"="'/3QU4L51GN/g' \
                 #| sed 's/'"!"'/3XCL4M4T10N/g' \
-            (( DEBUG )) && echo -e "0.${RED}${FUNCNAME[1]} that value ${RED},,${CYAN}${statement}${RED}''${RESET}"
+            local -i _DEBUG=${DEBUG:-0}
+						(( _DEBUG )) && echo -e "0.${RED}${FUNCNAME[1]} that value ${RED},,${CYAN}${statement}${RED}''${RESET}"
             # exit 0
             local inputo=""
             inputo=$(echo """${statement}""" \
@@ -1937,7 +1939,7 @@ function _run_command(){
                 | sed 's/'" ~~ "'/~/g' \
                 | sed 's/'"~~"'/~/g' \
             )
-            (( DEBUG )) && echo -e "0.${RED}${FUNCNAME[1]} inputo ${RED},,${GREEN}${inputo}${RED}''${RESET}"
+            (( _DEBUG )) && echo -e "0.${RED}${FUNCNAME[1]} inputo ${RED},,${GREEN}${inputo}${RED}''${RESET}"
             # echo $inputo
             # return 0
             #    0     1    2   3
@@ -1961,17 +1963,17 @@ function _run_command(){
                 }
                 fi
                 value_one="${inputo%=*}"  # retain the part before the =
-                (( DEBUG )) && echo -e "=value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
+                (( _DEBUG )) && echo -e "=value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
                 value_two="${inputo##*=}"  # retain the part after the =
-                (( DEBUG )) && echo -e "=value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+                (( _DEBUG )) && echo -e "=value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
                 # value_one=$(echo -n "${inputo}" | cut -d'=' -f1 | trim)
-                # (( DEBUG )) && echo -e "=value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
+                # (( _DEBUG )) && echo -e "=value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
                 # value_two=$(echo -n "${inputo}" | cut -d'=' -f2- | trim)
-                # (( DEBUG )) && echo -e "=value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+                # (( _DEBUG )) && echo -e "=value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
                 value_one=$(convert_null "${value_one}")
-                (( DEBUG )) && echo -e "=value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
+                (( _DEBUG )) && echo -e "=value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
                 value_two=$(convert_null "${value_two}")
-                (( DEBUG )) && echo -e "=value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+                (( _DEBUG )) && echo -e "=value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
                 TESTING="${RESET}${FUNCNAME[0]} that value ${YELLOW_OVER_DARKBLUE}${value_one}${RESET}${CYAN} same as ${YELLOW_OVER_GRAY241}${value_two}${RESET}"
                 if [[ "${value_one}" == "${value_two}" ]] ; then
                 {
@@ -1997,14 +1999,14 @@ function _run_command(){
                 }
                 fi
                 value_one="${inputo%!*}"  # retain the part before the !
-                (( DEBUG )) && echo -e "!value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
+                (( _DEBUG )) && echo -e "!value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
                 value_two="${inputo##*!}"  # retain the part after the !
-                (( DEBUG )) && echo -e "!value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+                (( _DEBUG )) && echo -e "!value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
 
                 value_one=$(convert_null "${value_one}")
-                (( DEBUG )) && echo -e "!value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
+                (( _DEBUG )) && echo -e "!value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
                 value_two=$(convert_null "${value_two}")
-                (( DEBUG )) && echo -e "!value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+                (( _DEBUG )) && echo -e "!value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
                 TESTING="${FUNCNAME[0]} that value ${YELLOW_OVER_DARKBLUE}${value_one}${RESET}${CYAN} not equal ${YELLOW_OVER_GRAY241}${value_two}${RESET}"
                 if [[ "${value_one}" != "${value_two}" ]] ; then
                 {
@@ -2031,19 +2033,19 @@ function _run_command(){
                 }
                 fi
                 value_one="${inputo%~*}"  # retain the part before the ~
-                (( DEBUG )) && echo -e "~value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
+                (( _DEBUG )) && echo -e "~value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
                 value_two="${inputo##*~}"  # retain the part after the ~
-                (( DEBUG )) && echo -e "~value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+                (( _DEBUG )) && echo -e "~value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
 
                 value_one=$(convert_null "${value_one}")
-                (( DEBUG )) && echo -e "~value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
+                (( _DEBUG )) && echo -e "~value_one:${RED},,${YELLOW_OVER_DARKBLUE}$value_one${RED}''${RESET}"
                 value_two=$(convert_null "${value_two}")
-                (( DEBUG )) && echo -e "~value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
+                (( _DEBUG )) && echo -e "~value_two:${RED},,${YELLOW_OVER_GRAY241}$value_two${RED}''${RESET}"
 
                 TESTING="${FUNCNAME[1]} that value ${YELLOW_OVER_DARKBLUE}${value_one}${RESET}${CYAN} to contain ${YELLOW_OVER_GRAY241}${value_two}${RESET}"
                 if [[ "${value_one}" == *"${value_two}"* ]] ; then
                 {
-                    # (( DEBUG )) &&
+                    # (( _DEBUG )) &&
                     # echo -e "~caller:${RED},,${YELLOW_OVER_DARKBLUE}$(caller)${RED}''${RESET}"
                     # passed "${FUNCNAME[1]}"
                     local C="${THISSCRIPTNAME}:${BASH_LINENO[0]}"
@@ -3285,7 +3287,7 @@ fi
             local query=""
             local install_result=""
             local err_buff=0
-            # local DEBUG=1
+            # local _DEBUG=1
 
             if [[ ${_OS:-} == "brew" ]] ; then
             {
@@ -3311,7 +3313,7 @@ fi
                   echo "rpm read packages"
                 fi
                 packages=$(rpm -qa)
-                # (( DEBUG )) && echo "\n rpm \n \n $packages \n \n rpm"
+                # (( _DEBUG )) && echo "\n rpm \n \n $packages \n \n rpm"
 
             }
             elif [[ ${_OS:-} != "brew" ]] && ( ( command -v apt >/dev/null 2>&1; ) && ( command -v dpkg >/dev/null 2>&1; ) ) ; then
@@ -3805,8 +3807,8 @@ fi
             echo "${KIND}"
         }
         PROCESSOR_ERROR=$(test_positives)
-        # DEBUG test_positives echo "${PROCESSOR_ERROR}"
-        # DEBUG test_positives exit 1
+        # _DEBUG test_positives echo "${PROCESSOR_ERROR}"
+        # _DEBUG test_positives exit 1
         #
         # C H E C K   H O W   C O M P U T E R   H A N D L E S   E R R O R S   --End
         #
@@ -5395,7 +5397,6 @@ function determine_os_and_fire_action() {
   local FUNCTION_TO_CALL=""
   local PARAMETERS="${*:-}"
   local -i _DEBUG=${DEBUG:-0}
-  # local -i DEBUG=0
   local -i _err=0
   # Check operating systems
   # echo  ${@}
@@ -6375,7 +6376,6 @@ function enforce_web_is_reachable(){
   msg=$(curl -I --connect-timeout 5 --max-time 10 "${_domain}" 2>&1; )
   _err=$?
   local -i _DEBUG=${DEBUG:-1}
-  #local DEBUG=1
   (( _DEBUG )) && echo enforce_web_is_reachable curl -I --connect-timeout 5  --max-time 10 "${1}"
   (( _DEBUG )) && echo enforce_web_is_reachable curl exit code $_err
   local TESTING="web address ${BRIGHT_BLUE87}««${RED}${1}${BRIGHT_BLUE87}»»${LIGHTYELLOW} is reachable"
@@ -6656,7 +6656,6 @@ function _remove_dmgs_app_if_exists() {
   local -i _DEBUG=${DEBUG:-0}
   local APPDIR="${1}"
   [[ -n "${APPDIR}" ]] && APPDIR="$(basename "${1}")"
-  DEBUG=1
   if (( _DEBUG )) ; then
   {
     echo "        APPDIR 1: <${1}>"
@@ -6684,8 +6683,8 @@ function _process_dmgs_dmg_or_zip() {
   [[ -n "${APPDIR}" ]] && APPDIR="$(basename "${4}")"
   local UNZIPDIR="${5}"
   [[ -n "${UNZIPDIR}" ]] && UNZIPDIR="$(basename "${5}")"
-  DEBUG=1
-  if (( DEBUG )) ; then
+  local -i _DEBUG=${DEBUG:-0}
+  if (( _DEBUG )) ; then
   {
     echo "     extension 1: <${1}>"
     echo "DOWNLOADFOLDER 2: <${2}>"
@@ -6762,7 +6761,6 @@ function _trust_dmgs_application() {
   local -i _DEBUG=${DEBUG:-0}
   local APPDIR="${1}"
   [[ -n "${APPDIR}" ]] && APPDIR="$(basename "${1}")"
-  DEBUG=1
   if (( _DEBUG )) ; then
   {
     echo "        APPDIR 1: <${1}>"
