updated loader to consider wget and curl

diff --git a/struct_testing b/struct_testing
--- a/struct_testing
+++ b/struct_testing
@@ -2088,7 +2088,7 @@ function _run_command(){
             #    _if_not_contains  && run_this
             #
             # or
-            # 
+            #
             # echo "${policies}" > temp.xml
             # if ! _if_not_contains temp.xml "{1,}" ; then
             # {
@@ -2135,11 +2135,11 @@ function _run_command(){
 
         function _if_contains(){
              # Sample use
-             # 
+             #
              # _if_contains && run_this
-             # 
+             #
              # or
-             # 
+             #
              # echo "${policies}" > temp.xml
              # if _if_contains temp.xml "{1,}" ; then
              # {
@@ -3525,7 +3525,7 @@ enter_last_only_removed() {
 # } # end execute_as_sudo
 function _find_downloads_folder(){
   # Sample Use
-  # 
+  #
   #      local DOWNLOADFOLDER="$(_find_downloads_folder)"
   #      enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
   #      cd "${DOWNLOADFOLDER}"
@@ -4273,7 +4273,7 @@ function _remove_downloaded_codename_or_err(){
   local DOWNLOADFOLDER_CODENAME="${2}"
   if [ $_err -eq 0 ] ; then
   {
-    if it_exists_with_spaces "${DOWNLOADFOLDER_CODENAME}"; then 
+    if it_exists_with_spaces "${DOWNLOADFOLDER_CODENAME}"; then
     {
       Message Removing Downloaded file "${DOWNLOADFOLDER_CODENAME}"
       rm "${DOWNLOADFOLDER_CODENAME}"
@@ -4515,20 +4515,38 @@ function raise_to_sudo_and_user_home() {
       local USER_HOME=$HOME
     }
     fi
-    local -r provider="$USER_HOME/_/clis/execute_command_intuivo_cli/execute_boot_basic.sh"
-    echo source "${provider}"
     # shellcheck disable=SC1090
-    [   -e "${provider}"  ] && source "${provider}"
-    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/execute_boot_basic.sh -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
-    if ( command -v failed >/dev/null 2>&1; ) ; then
-    {
-      return 0
-    }
+    local -r provider="$USER_HOME/_/clis/execute_command_intuivo_cli/execute_boot_basic.sh"
+    local _err=0 bootbasicsource
+    if [   -e "${provider}"  ] ; then
+      echo "Loading locally"
+      bootbasicsource="""$(<"${provider}")"""
+      _err=$?
+      [ $_err -gt 0 ] &&  echo -e "\n \n  ERROR! Loading execute_boot_basic.sh. running 'source locally' returned error did not download or is empty err:$_err  \n \n  " && exit 1
     else
-    {
-      echo -e "\n \n  ERROR! Loading execute_boot_basic.sh \n \n "
-      exit 1;
-    }
+      if ( command -v curl >/dev/null 2>&1; )  ; then
+        echo "Loading execute_boot_basic.sh from the net using curl "
+        bootbasicsource="""$(curl https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/execute_boot_basic.sh  -so -   2>/dev/null )"""  #  2>/dev/null suppress only curl download messages, but keep curl output for variable
+        _err=$?
+        [ $_err -gt 0 ] &&  echo -e "\n \n  ERROR! Loading execute_boot_basic.sh. running 'curl' returned error did not download or is empty err:$_err  \n \n  " && exit 1
+      elif ( command -v wget >/dev/null 2>&1; ) ; then
+        echo "Loading execute_boot_basic.sh from the net using wget "
+        bootbasicsource="""$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/execute_boot_basic.sh -O -   2>/dev/null )"""  #  2>/dev/null suppress only wget download messages, but keep wget output for variable
+        _err=$?
+        [ $_err -gt 0 ] &&  echo -e "\n \n  ERROR! Loading execute_boot_basic.sh. running 'wget' returned error did not download or is empty err:$_err  \n \n  " && exit 1
+      else
+        echo -e "\n \n  ERROR! Loading execute_boot_basic.sh could not find wget or curl to download  \n \n "
+        exit 69
+      fi
+    fi
+    [[ -z "${bootbasicsource}" ]] && echo -e "\n \n  ERROR! Loading execute_boot_basic.sh. bootbasicsource did not download or is empty " && exit 1
+    echo "${bootbasicsource}">/tmp/struct_testing
+    source /tmp/struct_testing
+    _err=$?
+    [ $_err -gt 0 ] &&  echo -e "\n \n  ERROR! Loading execute_boot_basic.sh. Occured while running 'source' err:$_err  \n \n  " && exit 1
+    if  ! typeset -f on_int >/dev/null 2>&1; then
+      echo -e "\n \n  ERROR! Loading execute_boot_basic.sh. on_int function was not found.. was not loaded !!!  \n \n "
+      exit 69;
     fi
     return 0
   } # end load_execute_boot_basic_with_sudo
@@ -4652,12 +4670,12 @@ function enforce_ip_resolves(){
 } # end enforce_ip_resolves
 
 function _remove_dmgs_app_if_exists() {
-  # Sample use 
-  #       _remove_dmgs_app_if_exists "${APPDIR}" 
-  local APPDIR="${1}" 
+  # Sample use
+  #       _remove_dmgs_app_if_exists "${APPDIR}"
+  local APPDIR="${1}"
   [[ -n "${APPDIR}" ]] && APPDIR="$(basename "${1}")"
   DEBUG=1
-  if (( DEBUG )) ; then 
+  if (( DEBUG )) ; then
   {
     echo "        APPDIR 1: <${1}>"
     echo "  APPDIR after  : <${APPDIR}>"
@@ -4674,7 +4692,7 @@ function _remove_dmgs_app_if_exists() {
   return 0
 } # end _remove_dmgs_app_if_exists
 function _process_dmgs_dmg_or_zip() {
-  # Sample use 
+  # Sample use
   #     _process_dmgs_dmg_or_zip "${extension}" "${DOWNLOADFOLDER}" "${CODENAME}" "${APPDIR}" "${UNZIPDIR}"
   local extension="${1}"
   local DOWNLOADFOLDER="${2}"
@@ -4684,7 +4702,7 @@ function _process_dmgs_dmg_or_zip() {
   local UNZIPDIR="${5}"
   [[ -n "${UNZIPDIR}" ]] && UNZIPDIR="$(basename "${5}")"
   DEBUG=1
-  if (( DEBUG )) ; then 
+  if (( DEBUG )) ; then
   {
     echo "     extension 1: <${1}>"
     echo "DOWNLOADFOLDER 2: <${2}>"
@@ -4704,7 +4722,7 @@ function _process_dmgs_dmg_or_zip() {
   if [[ -n "${extension}" ]] && [[ "${extension}"  == "zip" ]] ; then
   {
     echo Unzipping downloaded
-    if it_exists_with_spaces "${DOWNLOADFOLDER}/${APPDIR}" ; then 
+    if it_exists_with_spaces "${DOWNLOADFOLDER}/${APPDIR}" ; then
     {
       echo Removing previous found unzipped
       rm -rf "${DOWNLOADFOLDER}/${APPDIR}"
@@ -4731,12 +4749,12 @@ function _process_dmgs_dmg_or_zip() {
 } # end _process_dmgs_dmg_or_zip
 
 function _trust_dmgs_application() {
-  # Sample use 
+  # Sample use
   #  _trust_dmgs_application "${APPDIR}"
-  local APPDIR="${1}" 
+  local APPDIR="${1}"
   [[ -n "${APPDIR}" ]] && APPDIR="$(basename "${1}")"
   DEBUG=1
-  if (( DEBUG )) ; then 
+  if (( DEBUG )) ; then
   {
     echo "        APPDIR 1: <${1}>"
     echo "  APPDIR after  : <${APPDIR}>"
@@ -4751,17 +4769,17 @@ function _trust_dmgs_application() {
 } # end  _trust_dmgs_application
 
 function _install_dmgs_dmg__64() {
-  # Sample use 
+  # Sample use
   # local target_name="LittleSnitch-4.6.dmg"
   # local target_app="Little Snitch 4.6/Little Installer.app"
-  # local target_url="https://www.obdev.at/ftp/pub/Products/littlesnitch/LittleSnitch-4.6.dmg"  
+  # local target_url="https://www.obdev.at/ftp/pub/Products/littlesnitch/LittleSnitch-4.6.dmg"
   #  _install_dmgs_dmg__64 "${target_name}" "${target_app}" "${target_url}"
   #
   #  or zip
   #
   # local target_name="BetterTouchTool.zip"
   # local target_app="BetterTouchTool.app"
-  # local target_url="https://raw.githubusercontent.com/danielng01/product-builds/master/iris/macos/Iris-1.2.0-OSX.zip"  
+  # local target_url="https://raw.githubusercontent.com/danielng01/product-builds/master/iris/macos/Iris-1.2.0-OSX.zip"
   # _install_dmgs_dmg__64 "${target_name}" "${target_app}" "${target_url}"
   #
   local CODENAME="${1}"
@@ -4794,26 +4812,26 @@ function _install_dmgs_dmg__64() {
   directory_exists_with_spaces "${DOWNLOADFOLDER}"
 
   _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
-  _remove_dmgs_app_if_exists "${APPDIR}" 
+  _remove_dmgs_app_if_exists "${APPDIR}"
 
   _process_dmgs_dmg_or_zip "${extension}" "${DOWNLOADFOLDER}" "${CODENAME}" "${APPDIR}" "${UNZIPDIR}"
 
   directory_exists_with_spaces "/Applications/${APPDIR}"
   ls -d "/Applications/${APPDIR}"
-  
+
   _trust_dmgs_application "${APPDIR}"
   return 0
 } # end _install_dmgs_dmg__64
 
 function _install_dmgs_list(){
-  # Sample use 
+  # Sample use
   #
   #     local TARGET_URL
   #     TARGET_URL="VSCode-darwin.zip|Visual Studio Code - Insiders.app|https://code.visualstudio.com/sha/download?build=insider&os=darwin"
   #     enforce_variable_with_value TARGET_URL "${TARGET_URL}"
   #     _install_dmgs_list "${TARGET_URL}"
   # or
-  #    local installlist 
+  #    local installlist
   #    installlist="
   #      Caffeine.dmg|Caffeine/Caffeine.app|https://github.com/IntelliScape/caffeine/releases/download/1.1.3/Caffeine.dmg
   #      Keybase.dmg|Keybase App/Keybase.app|https://prerelease.keybase.io/Keybase.dmg
@@ -4836,13 +4854,13 @@ function _install_dmgs_list(){
   #      dbeaver-ce-7.3.4-macos.dmg|DBeaver Community/DBeaver.app|https://download.dbeaver.com/community/7.3.4/dbeaver-ce-7.3.4-macos.dmg
   #      Inkscape-1.0.2.dmg|Inkscape/Inkscape.app|https://media.inkscape.org/dl/resources/file/Inkscape-1.0.2.dmg
   #      LittleSnitch-4.6.dmg|Little Snitch 4.6/Little Installer.app|https://www.obdev.at/ftp/pub/Products/littlesnitch/LittleSnitch-4.6.dmg
-  #    "  
+  #    "
   #     _install_dmgs_dmg__64 "${installlist}"
   # Pending how to do pkg automatic?   # 1Password.pkg|https://c.1password.com/dist/1P/mac7/1Password-7.7.pkg
   local installlist one  target_name target_url target_app app_name # extension
   installlist="${*}"
   DEBUG=1
-  if (( DEBUG )) ; then 
+  if (( DEBUG )) ; then
   {
     echo "        installlist 1: <${*}>"
     echo "  installlist after  : <${installlist}>"
