get_architecture added to cover more robust os recognition with uname -i and uname -a

diff --git a/struct_testing b/struct_testing
--- a/struct_testing
+++ b/struct_testing
@@ -473,37 +473,53 @@ CERO="\033[01;0m"
           # [ -n "${CAN_I_RUN_SUDO+x}" ] && echo "CAN_I_RUN_SUDO 12"
           # [ -n "${SUDO_USER+x}" ] && echo "SUDO_USER 111"
           # ( declare -p "HOME" ) && echo "HOME 2"
+          local _err_arriving=$?
           typeset -r TESTING="that variable is listed and: ${CYAN}${1}${LIGHTYELLOW} and has value: ${RESET}<${YELLOW_OVER_DARKBLUE}${2}${RESET}>"
+          if [ ${_err_arriving} -gt 0 ] ; then
+          {
+             warning _err_arriving:${_err_arriving}
+             warning failed $0 $*
+             failed "${TESTING}" ${RED} Stopped executing becuase it arrived with \$_ERR not Zero
+          }
+          fi
           local -i _seemsempty_=0
-          (( DEBUG )) && echo -e "${FUNCNAME[0]}"
-          (( DEBUG )) && echo "x${1}x" -assume existing variable for this part
-          (( DEBUG )) && echo "x${2}x" -assume existing variable for this part
+          if (( DEBUG )) ; then
+            echo -e "${FUNCNAME[0]}"
+            echo "x${1}x" -assume existing variable for this part
+            echo "x${2}x" -assume existing variable for this part
+          fi
           [[ "x${2}x" = "xx" ]] && _seemsempty_=1
-          (( DEBUG )) && [[ "x${2}x" = "xx" ]] && echo seems empty
-          (( DEBUG )) && ( typeset -p "${1}"  &>/dev/null  ) && echo "1 defined 1"
-          (( DEBUG )) && [ -n "${2+x}" ]  && echo "1 defined 2"
-          (( DEBUG )) && ( typeset -p "${1}"  &>/dev/null ) &&  [ -n "${2+x}" ]  && echo "1 declared,defined and with value not empty 3"
-          (( DEBUG )) && ( ( typeset -p "${1}"  &>/dev/null  ) || echo "1 not defined 1")
-          (( DEBUG )) && ( ! typeset -p "${1}"  &>/dev/null  ) && echo "1 not defined 2"
-          (( DEBUG )) && ( env | grep "${1}"  &>/dev/null  ) && echo "2 not in env "
-          (( DEBUG )) && [ -n "${2+x}" ]  && echo "2 failed empty 8"
-          (( DEBUG )) && [ -n "${2-x}" ]  && echo "2 failed empty 7"
-          (( DEBUG )) && [ -z "${2+x}" ]  && echo "2 failed empty 9"
-          (( DEBUG )) && [ -z "${2-x}" ]  && echo "2 failed empty 10"
-          # echo QWER - assume non existant variable for this part
-          # ( typeset -p "QWER"  &>/dev/null  ) && echo "QWER defined 1"
-          # [ -n "${QWER+x}" ]  && echo "QWER defined 2"
-          # ( typeset -p "QWER"  &>/dev/null ) &&  [ -n "${QWER+x}" ]  && echo "QWER defined 3"
-          # ( typeset -p "QWER"  &>/dev/null  ) || echo "QWER not defined 1"
-          # ( ! typeset -p "QWER"  &>/dev/null  ) && echo "QWER not defined 2"
-          # echo bye
-          # exit 0
+          if (( DEBUG )) ; then
+            if [[ "x${2}x" = "xx" ]] ; then
+              echo seems empty
+            fi
+            ( typeset -p "${1}"  &>/dev/null  ) && echo "1 defined 1"
+            [ -n "${2+x}" ]  && echo "1 defined 2"
+            ( typeset -p "${1}"  &>/dev/null ) &&  [ -n "${2+x}" ]  && echo "1 declared,defined and with value not empty 3"
+            ( ( typeset -p "${1}"  &>/dev/null  ) || echo "1 not defined 1")
+            ( ! typeset -p "${1}"  &>/dev/null  ) && echo "1 not defined 2"
+            ( env | grep "${1}"  &>/dev/null  ) && echo "2 not in env "
+            [ -n "${2+x}" ]  && echo "2 failed empty 8"
+            [ -n "${2-x}" ]  && echo "2 failed empty 7"
+            [ -z "${2+x}" ]  && echo "2 failed empty 9"
+            [ -z "${2-x}" ]  && echo "2 failed empty 10"
+            # echo QWER - assume non existant variable for this part
+            # ( typeset -p "QWER"  &>/dev/null  ) && echo "QWER defined 1"
+            # [ -n "${QWER+x}" ]  && echo "QWER defined 2"
+            # ( typeset -p "QWER"  &>/dev/null ) &&  [ -n "${QWER+x}" ]  && echo "QWER defined 3"
+            # ( typeset -p "QWER"  &>/dev/null  ) || echo "QWER not defined 1"
+            # ( ! typeset -p "QWER"  &>/dev/null  ) && echo "QWER not defined 2"
+            # echo bye
+            # exit 0
+          fi
           (( _seemsempty_ )) && echo -e "${RED} 𝞦 enforce_variable_with_value \\n${BASH_SOURCE[1]}:${BASH_LINENO[1]} ${FUNCNAME[-0]}(...) \\n${BASH_SOURCE[1]}:${BASH_LINENO[0]} ${FUNCNAME[1]}(...) \\n ${LIGHTYELLOW} ${TESTING} has failed "
           (( _seemsempty_ )) && failed "${TESTING}"
           (( _seemsempty_ )) && exit 1
           if (( typeset -p "${1}"  &>/dev/null ) &&  [ -n "${2+x}" ]) ; then
           {
-              (( DEBUG )) && echo -e "${LIGHTGREEN} ✔ ${LIGHTYELLOW} ${TESTING} has passed "
+              if (( DEBUG )) ; then
+                echo -e "${LIGHTGREEN} ✔ ${LIGHTYELLOW} ${TESTING} has passed "
+              fi
               return 0
           }
           fi
@@ -1069,7 +1085,7 @@ CERO="\033[01;0m"
             {
                 while read -r ONE_FILE; do
                 if [ -n "${ONE_FILE}" ] ; then # if not empty
-                    TESTING="that file ${CYAN}${ONE_FILE}${LIGHTYELLOW} exists"
+                    TESTING="that file „${CYAN}${ONE_FILE}${LIGHTYELLOW}” exists"
                     # DEBUG echo -e "${BASH_SOURCE[0]} ->\n  .. ${FUNCNAME[0]}():$ONE_FILE"
                     if it_exists_with_spaces "${ONE_FILE}" ; then
                     {
@@ -3714,10 +3730,64 @@ function _find_downloads_folder(){
   #      cd "${DOWNLOADFOLDER}"
   #      _download_mac "${TARGET_URL}" "${DOWNLOADFOLDER}"
   #
+  local DOWNLOADFOLDER=""
+  local -i _err=0
+  # first try typical assignation
+  # check operation systems
+  if [[ "$(uname)" == "Darwin" ]] ; then
+    # Do something under Mac OS X platform
+    DOWNLOADFOLDER=/Users/"${SUDO_USER}"/Downloads
+  elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
+    # Do something under GNU/Linux platform
+    DOWNLOADFOLDER=/home/"${SUDO_USER}"/Downloads
+  elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then
+    # Do something under Windows NT platform
+    DOWNLOADFOLDER=/C/Users/"${SUDO_USER}"/Downloads
+    # nothing here
+  fi
+  if [ -n "${DOWNLOADFOLDER}" ] ; then
+  {
+    if it_exists_with_spaces "${DOWNLOADFOLDER}" ; then
+    {
+      cd "${DOWNLOADFOLDER}"
+      echo -n "${DOWNLOADFOLDER}"
+      return 0
+    }
+    fi
+  }
+  fi
+
+
   if ( command -v xdg-user-dir >/dev/null 2>&1; ) ; then
   {
     enforce_variable_with_value SUDO_USER "${SUDO_USER}"
     local DOWNLOADFOLDER="$(su - "${SUDO_USER}" -c 'xdg-user-dir DOWNLOAD')"
+    _err=$?
+    # this could have failed live above, because of login problems or broken user, or lack of rights, etc
+    # so try again with normal call
+    if [ -z "${DOWNLOADFOLDER}" ] || [ ${_err} -gt 0 ] ; then
+    {
+      # getting /root/Downloads ?
+      DOWNLOADFOLDER="$(xdg-user-dir DOWNLOAD)"
+      _err=$?
+    }
+    fi
+    # check again for value in case that fails also
+    #  if so, then create with mkdir process, I assume this will always work, #nevermakeassumptions btw
+    if [ -z "${DOWNLOADFOLDER}" ] || [ ${_err} -gt 0 ] ; then
+    {
+      DOWNLOADFOLDER="$(mktemp -d 2>/dev/null || mktemp -d -t 'tempdownloads')"
+      _err=$?
+    }
+    fi
+    # check empty of error
+    if [ -z "${DOWNLOADFOLDER}" ] || [ ${_err} -gt 0 ] ; then
+    {
+      return 1  # here one is for error
+      exit 1
+    }
+    fi
+    # finally check we got a value
     enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
     cd "${DOWNLOADFOLDER}"
     echo -n "${DOWNLOADFOLDER}"
@@ -4260,6 +4330,41 @@ function function_exists_with_spaces() {
             unset TESTING
 } # end function_exists_with_spaces
 
+function get_architecture(){
+  # How to use
+  #    FUNCTION_TO_CALL=$(get_architecture "debian")
+  # > _debian__64
+  # > _debian__32
+  #    FUNCTION_TO_CALL=$(get_architecture "${DISTRO}")
+  #
+  local system_nick="${1}"
+  local return_function_to_call=""
+  if [[ "$(uname -i)" == "x86_64" ]] ; then
+  {
+    return_function_to_call="_${system_nick}__64"
+  }
+  elif [[ "$(uname -i)" == "i686"   ]] ; then
+  {
+    return_function_to_call="_${system_nick}__32"
+  }
+  fi
+  if [ -z ${return_function_to_call} ] || [[ "${return_function_to_call}" =~ 'nknown' ]] ; then
+  {
+     if [[ "${uname -a}" =~  'x86_64' ]] ; then
+     {
+       return_function_to_call="_${system_nick}__64"
+     }
+     fi
+     if [[ "${uname -a}" =~  'i686' ]] ; then
+     {
+       return_function_to_call="_${system_nick}__32"
+     }
+     fi
+  }
+  fi
+  echo -n ${return_function_to_call}
+  return 0
+} # end get_architecture
 
 function determine_os_and_fire_action() {
   # Interface
@@ -4350,7 +4455,7 @@ function determine_os_and_fire_action() {
                 # $ echo $VERSION
                 # 17 (Beefy Miracle)
                 DISTRO=$ID
-    }
+        }
         fi
     }
     fi
@@ -4362,62 +4467,24 @@ function determine_os_and_fire_action() {
 
     if [[ "$DISTRO" == *"edora"* ]]; then
     {
-        if [[ "$(uname -i)" == "x86_64" ]] ; then
-        {
-            FUNCTION_TO_CALL='_fedora__64'
-            PARAMETERS="$@"
-        }
-        elif [[ "$(uname -i)" == "i686"   ]] ; then
-        {
-            FUNCTION_TO_CALL='_fedora__32'
-            PARAMETERS="$@"
-        }
-        fi
+      FUNCTION_TO_CALL=$(get_architecture "fedora")
+      PARAMETERS="$@"
     }
     elif [[ "$DISTRO" == *"untu"* ]]; then
     {
-        # ubuntu lsb_release -i | sed 's/Distributor\ ID://g' = \tUbuntu\n
-        if [[ "$(uname -i)" == "x86_64" ]] ; then
-        {
-           FUNCTION_TO_CALL='_ubuntu__64'
-           PARAMETERS="$@"
-        }
-        elif [[ "$(uname -i)" == "i686"   ]] ; then
-        {
-           FUNCTION_TO_CALL='_ubuntu__32'
-           PARAMETERS="$@"
-        }
-        fi
+      # ubuntu lsb_release -i | sed 's/Distributor\ ID://g' = \tUbuntu\n
+      FUNCTION_TO_CALL=$(get_architecture "ubuntu")
+      PARAMETERS="$@"
     }
     elif [[ "$DISTRO" == *"bian"* ]]; then
     {
-        # ubuntu lsb_release -i | sed 's/Distributor\ ID://g' = \tUbuntu\n
-        if ( uname -a | grep x86_64 >/dev/null 2>&1; )  ; then
-        {
-           FUNCTION_TO_CALL='_debian__64'
-           PARAMETERS="$@"
-        }
-        elif ( uname -a | grep i686 >/dev/null 2>&1; )  ; then
-        {
-           FUNCTION_TO_CALL='_debian__32'
-           PARAMETERS="$@"
-        }
-        fi
+      FUNCTION_TO_CALL=$(get_architecture "debian")
+      PARAMETERS="$@"
     }
     else
     {
-      # ubuntu lsb_release -i | sed 's/Distributor\ ID://g' = \tUbuntu\n
-        if [[ "$(uname -i)" == "x86_64" ]] ; then
-        {
-           FUNCTION_TO_CALL="_${DISTRO}__64"
-           PARAMETERS="$@"
-        }
-        elif [[ "$(uname -i)" == "i686"   ]] ; then
-        {
-           FUNCTION_TO_CALL="_${DISTRO}__32"
-           PARAMETERS="$@"
-        }
-        fi
+      FUNCTION_TO_CALL=$(get_architecture "${DISTRO}")
+      PARAMETERS="$@"
     }
     fi
     (( DEBUG )) && echo "FUNCTION_TO_CALL: $FUNCTION_TO_CALL"
@@ -4602,6 +4669,7 @@ function _do_not_downloadtwice(){
   local TARGET_URL="${1}"
   enforce_parameter_with_value 1 TARGET_URL "${TARGET_URL}" "https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm"
   local DOWNLOADFOLDER="${2}"
+  Comment DOWNLOADFOLDER:„${DOWNLOADFOLDER}”
   enforce_parameter_with_value 2 DOWNLOADFOLDER "${DOWNLOADFOLDER}" "$USER_HOME/Downloads"
   file_exists_with_spaces "${DOWNLOADFOLDER}"
   local CODENAME="${3}"
@@ -4756,6 +4824,7 @@ function _install_rpm() {
     enforce_parameter_with_value 3 CODENAME "${CODENAME}" "teamviewer.x86_64.rpm"
     local -i LOOP="${4}"
     enforce_parameter_with_value 4 LOOP "${LOOP}" "1 or 2 or 0"
+    Comment testing "${DOWNLOADFOLDER}/${CODENAME}"
     file_exists_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"
     local TARGET_DOWNLOAD_PATH="${DOWNLOADFOLDER}/${CODENAME}"
     enforce_parameter_with_value COMPOSITE TARGET_DOWNLOAD_PATH "${TARGET_DOWNLOAD_PATH}" "$USER_HOME/Downloads/teamviewer.x86_64.rpm"
