replaced all exit 130 for exit 69 denial of service

diff --git a/struct_testing b/struct_testing
--- a/struct_testing
+++ b/struct_testing
@@ -110,7 +110,7 @@ function HOW_TO_LOAD_SEVERAL_FILES() {
         unset ONE_SCRIPT
         unset BASH_SCRIPTS
         unset provider
-        ( ( ! command -v type passed >/dev/null 2>&1;) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 130; )
+        ( ( ! command -v type passed >/dev/null 2>&1;) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
     } # end load_execute_commands_wget
     load_execute_commands_wget
 
@@ -124,7 +124,7 @@ function HOW_TO_LOAD_JUST_ONE_SCRIPT_LOCAL_AND_ONLINE_EXECUTE_COMMAND() {
         [ ! -d "/_/clis/execute_command_intuivo_cli/" ] && provider="https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/execute_command"
         local EXECOMCLI=$(curl $provider  2>/dev/null )   # suppress only curl download messages, but keep curl output for variable
         eval """${EXECOMCLI}"""
-        ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading execute_command \n \n " && exit 130; )
+        ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading execute_command \n \n " && exit 69; )
     } # end load_struct_testing_curl
     load_struct_testing_curl
 } # end HOW_TO_LOAD_JUST_ONE_SCRIPT_EXECUTE_COMMAND
@@ -137,7 +137,7 @@ function HOW_TO_LOAD_JUST_ONE_SCRIPT_LOCAL_AND_ONLINE_STRUCT_USING_CURL() {
         [ ! -d "/_/clis/execute_command_intuivo_cli/" ] && provider="https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing"
         local EXECOMCLI=$(curl $provider  2>/dev/null )   # suppress only curl download messages, but keep curl output for variable
         eval """${EXECOMCLI}"""
-        ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 130; )
+        ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
     } # end load_struct_testing_curl
     load_struct_testing_curl
 
@@ -151,7 +151,7 @@ function HOW_TO_LOAD_JUST_ONE_SCRIPT_LOCAL_AND_ONLINE_STRUCT_USING_WGET() {
         [   -e "${provider}"  ] && local EXECOMCLI=$(<"${provider}")
         [ ! -e "${provider}"  ] && local EXECOMCLI=$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )   # suppress only curl download messages, but keep curl output for variable
         [ ! -z "${EXECOMCLI}" ] && eval """${EXECOMCLI}"""
-        ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 130; )
+        ( ( ! command -v type passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
     } # end load_struct_testing_wget
     load_struct_testing_wget
 
@@ -163,7 +163,7 @@ function HOW_TO_LOAD_JUST_ONE_SCRIPT_ONLINE_ALWAYS_STRUCT_USING_WGET() {
         # HOW TO LOAD JUST ONE SCRIPT
         EXECOMCLI=$(wget --quiet --no-check-certificate https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )   # suppress only curl download messages, but keep curl output for variable
         eval """${EXECOMCLI}"""
-        ( ( ! command -v type passed >/dev/null 2>&1;) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 130; )
+        ( ( ! command -v type passed >/dev/null 2>&1;) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
     } # end load_struct_testing_wget
     load_struct_testing_wget
 
@@ -236,7 +236,7 @@ CERO="\033[01;0m"
         }
         function kill_execution() {
             echo -e " ☠ ${LIGHTPINK} KILL EXECUTION SIGNAL SEND ${RESET}"
-            exit 130;
+            exit 69;
         }
 
         function failed() {
@@ -266,9 +266,9 @@ CERO="\033[01;0m"
                 msg=$(echo "${msg}" | sed  -e 's/uit /uiting /g')
                 msg=$(echo "${msg}" | sed  -e 's/xit /xiting /g')
                 echo "${msg}"
-                [[ "${msg}" == *"anceling "* ]] && exit 130
-                [[ "${msg}" == *"uiting "* ]] && exit 130
-                [[ "${msg}" == *"xiting "* ]] && exit 130
+                [[ "${msg}" == *"anceling "* ]] && exit 69
+                [[ "${msg}" == *"uiting "* ]] && exit 69
+                [[ "${msg}" == *"xiting "* ]] && exit 69
                 return 1
             fi
         }
@@ -780,7 +780,7 @@ CERO="\033[01;0m"
     THISSCRIPTNAME=`basename "$0"`
 
     # TRAP
-    trap '{  \" `basename "$0"` KEYBOARD INTERRUPT.\"; exit 130; }' INT
+    trap '{  \" `basename "$0"` KEYBOARD INTERRUPT.\"; exit 69; }' INT
 
         #
         # Template:
