fixed some ubbound vars in mac

diff --git a/struct_testing b/struct_testing
--- a/struct_testing
+++ b/struct_testing
@@ -316,7 +316,7 @@ CERO="\033[01;0m"
                 (( _error_count-- ))
                 local -i _counter=0
                 local -i _counter_offset=0
-                echo -e " ☠ ${LIGHTPINK} ERROR STACK TRACE: ${len}  ${RESET}"  >&2
+                echo -e " ☠ ${LIGHTPINK} ERROR STACK TRACE: ${_error_count}  ${RESET}"  >&2
                 # echo -e "0000${BRIGHT_BLUE87} ${BASH_SOURCE[0]}:${BASH_LINENO[0]} \t\t  ${FUNCNAME[0]}() ${RESET}"  >&2
                 echo -e "${BRIGHT_BLUE87} ${__caller_script_name}:${__caller_line} \t\t  ${FUNCNAME[1]}() ${RESET}"  >&2
                 for (( _counter=1; _counter<${_error_count}; _counter++ )); do
@@ -621,61 +621,61 @@ CERO="\033[01;0m"
         } # end ensure
 
         function Installing() {
-            echo -e "${GREEN} Installing ${RED}${1}${GREEN}, ${RED}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
+            echo -e "${GREEN} Installing ${RED}${1-}${GREEN}, ${RED}${2-} ${GREEN}${3-} ${CYAN}${4-}, ${RED}${5-} ${GREEN}${6-} ${CYAN}${*:-7} ${GREEN}.${RESET}"
         } # end Installing
         alias installing=Installing
 
         function Downloading() {
-            echo -e "${GREEN} Downloading ${RED}${1}${GREEN}, ${RED}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
+            echo -e "${GREEN} Downloading ${RED}${1-}${GREEN}, ${RED}${2-} ${GREEN}${3-} ${CYAN}${4-}, ${RED}${5-} ${GREEN}${6-} ${CYAN}${*:-7} ${GREEN}.${RESET}"
         } # end Downloading
         alias downloading=Downloading
 
         function Loading() {
-            echo -e "${CYAN} Loading ${GREEN}${1}${GRAY241}, ${RED}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
+            echo -e "${CYAN} Loading ${GREEN}${1-}${GRAY241}, ${RED}${2-} ${GREEN}${3-} ${CYAN}${4-}, ${RED}${5-} ${GREEN}${6-} ${CYAN}${*:-7} ${GREEN}.${RESET}"
         } # end Loading
         alias loading=Loading
 
         function Creating() {
-            echo -e "${DARK_BLUE_OVER_PEACH} Creating ${YELLOW_OVER_DARKBLUE}${1}${GREEN}, ${LIGHTPINK_OVER_DARKBLUE}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
+            echo -e "${DARK_BLUE_OVER_PEACH} Creating ${YELLOW_OVER_DARKBLUE}${1-}${GREEN}, ${LIGHTPINK_OVER_DARKBLUE}${2-} ${GREEN}${3-} ${CYAN}${4-}, ${RED}${5-} ${GREEN}${6-} ${CYAN}${*:-7} ${GREEN}.${RESET}"
         } # end Loading
         alias creating=Creating
 
         function Skipping() {
-            echo -e "${DARK_BLUE_OVER_PEACH} Skipping ${YELLOW_OVER_DARKBLUE}${1}${GREEN}, ${LIGHTPINK_OVER_DARKBLUE}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
+            echo -e "${DARK_BLUE_OVER_PEACH} Skipping ${YELLOW_OVER_DARKBLUE}${1-}${GREEN}, ${LIGHTPINK_OVER_DARKBLUE}${2-} ${GREEN}${3-} ${CYAN}${4-}, ${RED}${5-} ${GREEN}${6-} ${CYAN}${*:-7} ${GREEN}.${RESET}"
         } # end Loading
         alias skipping=Skipping
 
         function Updating() {
-            echo -e "${ORANGE} Updating ${BRIGHT_BLUE87}${1}${GREEN}, ${YELLOW226}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
+            echo -e "${ORANGE} Updating ${BRIGHT_BLUE87}${1-}${GREEN}, ${YELLOW226}${2-} ${GREEN}${3-} ${CYAN}${4-}, ${RED}${5-} ${GREEN}${6-} ${CYAN}${*:-7} ${GREEN}.${RESET}"
         } # end Loading
         alias updating=Updating
 
         function Testing() {
-            echo -e "${CYAN} Testing ${PURPLE}${1}${GREEN}, ${RED}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
+            echo -e "${CYAN} Testing ${PURPLE}${1-}${GREEN}, ${RED}${2-} ${GREEN}${3-} ${CYAN}${4-}, ${RED}${5-} ${GREEN}${6-} ${CYAN}${*:-7} ${GREEN}.${RESET}"
         } # end Testing
         alias testing=Testing
 
         function Configuring() {
-            echo -e "${GREEN} Configuring ${RED}${1}${GREEN}, ${RED}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
+            echo -e "${GREEN} Configuring ${RED}${1-}${GREEN}, ${RED}${2-} ${GREEN}${3-} ${CYAN}${4-}, ${RED}${5-} ${GREEN}${6-} ${CYAN}${*:-7} ${GREEN}.${RESET}"
         } # end Configuring
         alias configuring=Configuring
 
         function Setting() {
-            echo -e "${GREEN} Setting ${RED}${1}${GREEN}, ${RED}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
+            echo -e "${GREEN} Setting ${RED}${1-}${GREEN}, ${RED}${2-} ${GREEN}${3-} ${CYAN}${4-}, ${RED}${5-} ${GREEN}${6-} ${CYAN}${*:-7} ${GREEN}.${RESET}"
         } # end Setting
         alias setting=Setting
 
         function Checking() {
-            echo -e "${GREEN} Checking ${RED}${1}${GREEN}, ${RED}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
+            echo -e "${GREEN} Checking ${RED}${1-}${GREEN}, ${RED}${2-} ${GREEN}${3-} ${CYAN}${4-}, ${RED}${5-} ${GREEN}${6-} ${CYAN}${*:-7} ${GREEN}.${RESET}"
         } # end Checking
         alias checking=Checking
 
         function Final() {
-            echo -e "${GREEN} Setting ${RED}${1}${GREEN}, ${RED}${2} ${GREEN}${3} ${CYAN}${4}, ${RED}${5} ${GREEN}${6} ${CYAN}${*:7} ${GREEN}.${RESET}"
+            echo -e "${GREEN} Setting ${RED}${1-}${GREEN}, ${RED}${2-} ${GREEN}${3-} ${CYAN}${4-}, ${RED}${5-} ${GREEN}${6-} ${CYAN}${*:-7} ${GREEN}.${RESET}"
         } # end Final
 
         function Showing() {
-            echo -e "${ORANGE} ø  ${PURPLE}${1}${ORANGE} ${CYAN}${2} ${DARKBLUE}${3} ${PURPLE_BLUE}${4} ${BRIGHT_BLUE87}${5} ${GREEN}${6} ${RED}${*:7} ${GREEN}.${RESET}"
+            echo -e "${ORANGE} ø  ${PURPLE}${1-}${ORANGE} ${CYAN}${2-} ${DARKBLUE}${3-} ${PURPLE_BLUE}${4-} ${BRIGHT_BLUE87}${5-} ${GREEN}${6-} ${RED}${*:-7} ${GREEN}.${RESET}"
             "${@}"
         } # end Showing
         alias showing=Showing
@@ -757,7 +757,7 @@ CERO="\033[01;0m"
             local msg1="$1"
             local msg2=$(echo -e "${*}" | cüt "${1}"  ;)
             # local msg2=$(echo "${*}" | sed 's/'"""${msg1}"""'//g'  ;)
-            echo  -e "${PURPLE}π‘“……… ${CYAN} ${msg1} ${DARKBLUE} ${msg2} ${LIGHTYELLOW}  ${CYAN} ${RESET}"
+            echo  -e "\n\n${PURPLE}π‘“……… ${CYAN} ${msg1} ${DARKBLUE} ${msg2} ${LIGHTYELLOW}  ${CYAN} ${RESET}\n\n"
         }
         alias working=Working
 
@@ -4936,7 +4936,9 @@ function _do_not_downloadtwice(){
   file_exists_with_spaces "${DOWNLOADFOLDER}"
   local CODENAME="${3}"
   enforce_parameter_with_value 3 CODENAME "${CODENAME}" "teamviewer.x86_64.rpm"
-  (( VERBOSE )) && echo  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
+
+  local -i _verbose=${VERBOSE:-0}
+  (( _verbose )) && echo  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
 
   if it_exists_with_spaces "${DOWNLOADFOLDER}/${CODENAME}" ; then
   {
