changed all DEBUG to use if..fi to avoid trap triggers

diff --git a/struct_testing b/struct_testing
--- a/struct_testing
+++ b/struct_testing
@@ -2628,7 +2628,9 @@ function _run_command(){
             # local DEBUG=1
             if ( ( command -v rpm >/dev/null 2>&1; ) && ( command -v dnf >/dev/null 2>&1; ) ); then
             {
-                (( DEBUG )) && echo "rpm read packages"
+                if (( DEBUG )) ; then
+                  echo "rpm read packages"
+                fi
                 packages=$(rpm -qa)
                 # (( DEBUG )) && echo "\n rpm \n \n $packages \n \n rpm"
 
@@ -2639,7 +2641,9 @@ function _run_command(){
             }
             elif ( command -v brew >/dev/null 2>&1; ) ; then
             {
-                (( DEBUG )) && echo "BREW list formulas"
+                if (( DEBUG )) ; then
+                  echo "BREW list formulas"
+                fi
                 # query=$(brew list --formula 2>&1)
                 query=$(su - "${SUDO_USER}" -c "brew list --formula" 2>&1)
                 # query=$(_run_command "brew list --formula"  2>&1)
@@ -2682,7 +2686,9 @@ function _run_command(){
               fi
               if ( ( command -v apt >/dev/null 2>&1; ) && ( command -v dpkg >/dev/null 2>&1; ) ) ; then
               {
-                (( DEBUG )) && echo "apt search using dpkg"
+                if (( DEBUG )) ; then
+                  echo "apt search using dpkg"
+                fi
                 # REF: https://www.cyberciti.biz/faq/find-out-if-package-is-installed-in-linux/
                 if query=$(dpkg-query -W -f='${Status} ${Version}\n' "$one_required"  2>&1) ; then
                 {
@@ -2698,40 +2704,68 @@ function _run_command(){
                 {
                     echo -e " ${RED}  NEED TO INSTALL ${YELLOW} $one_required${RESET} ${RED}...${query}"
                     missing="${missing} ${install_this}"
-                    (( DEBUG )) && echo  "${install_this}"
+                    if (( DEBUG )) ; then
+                      echo  "${install_this}"
+                    fi
                 }
                 fi
               }
               elif ( ( command -v rpm >/dev/null 2>&1; ) && ( command -v dnf >/dev/null 2>&1; ) ) ; then
               {
-                (( DEBUG )) && echo "rpm search loaded packages $one_required"
-                (( DEBUG )) && echo "rpm --------1"
-                (( DEBUG )) && echo "${packages}" | grep "$one_required"
-                (( DEBUG )) && echo "rpm --------2"
-                (( DEBUG )) && echo "${packages}" | grep "$one_required"| grep "^$one_required"
-                (( DEBUG )) && echo "rpm --------3"
-                (( DEBUG )) && echo "${packages}" | egrep "$one_required"| grep "^$one_required" | cut -d'-' -f1
-                (( DEBUG )) && echo "rpm --------4"
-                (( DEBUG )) && echo "rpm RETURNED:$?"
+                if (( DEBUG )) ; then
+                  echo "rpm search loaded packages $one_required"
+                fi
+                if (( DEBUG )) ; then
+                  echo "rpm --------1"
+                fi
+                if (( DEBUG )) ; then
+                  echo "${packages}" | grep "$one_required"
+                fi
+                if (( DEBUG )) ; then
+                  echo "rpm --------2"
+                fi
+                if (( DEBUG )) ; then
+                  echo "${packages}" | grep "$one_required"| grep "^$one_required"
+                fi
+                if (( DEBUG )) ; then
+                  echo "rpm --------3"
+                fi
+                if (( DEBUG )) ; then
+                  echo "${packages}" | egrep "$one_required"| grep "^$one_required" | cut -d'-' -f1
+                fi
+                if (( DEBUG )) ; then
+                  echo "rpm --------4"
+                fi
+                if (( DEBUG )) ; then
+                  echo "rpm RETURNED:$?"
+                fi
                 if     ( echo "${packages}" | grep "$one_required" >/dev/null 2>&1; ) \
                     && ( echo "${packages}" | grep "$one_required"| grep "^$one_required" >/dev/null 2>&1; ) \
                     && ( echo "${packages}" | egrep "$one_required"| grep "^$one_required" | cut -d'-' -f1  >/dev/null 2>&1; ) ; then
                 {
-                    (( DEBUG )) && echo "rpm passed"
+                    if (( DEBUG )) ; then
+                      echo "rpm passed"
+                    fi
                     passed " ${GREEN} $one_required ${YELLOW} INSTALLED${RESET} ."
                 }
                 else
                 {
-                    (( DEBUG )) && echo "rpm failed"
+                    if (( DEBUG )) ; then
+                      echo "rpm failed"
+                    fi
                     echo -e " ${RED}  NEED TO INSTALL ${YELLOW} $one_required${RESET} ${RED}...${query}"
                     missing="${missing} ${install_this}"
-                    (( DEBUG )) && echo  "${install_this}"
+                    if (( DEBUG )) ; then
+                      echo  "${install_this}"
+                    fi
                 }
                 fi
               }
               elif ( command -v brew >/dev/null 2>&1; ) ; then
               {
-                (( DEBUG )) && echo "brew"
+                if (( DEBUG )) ; then
+                  echo "brew"
+                fi
                 # CHECK_INSTALLED=$(brew ls --versions "${one_required}")
                 # query=$(brew list --formula 2>&1)
                 # one_required="nano"
@@ -2762,27 +2796,36 @@ function _run_command(){
             # Check Requirements OS Ubuntu 14.04 REF: https://wiki.postgresql.org/wiki/Compile_and_Install_from_source_code#Ubuntu
             if [[ -n "${missing}" ]] ; then
             {
-              (( DEBUG )) && echo "There are missing"
+              if (( DEBUG )) ; then
+                echo "There are missing"
+              fi
               missing=$(echo -n ${missing} | sed -e 's/^[[:space:]]*//' ) # trim_start_space
               echo -e " ${CYAN} Installing missing packages: ${YELLOW} ${missing} ${RESET} ."
               if ( ( command -v apt >/dev/null 2>&1; )  && ( command -v dpkg >/dev/null 2>&1; ) ); then
               {
-                (( DEBUG )) && echo "apt install"
+                if (( DEBUG )) ; then
+                  echo "apt install"
+                fi
                 install_result=$(sudo apt install ${missing} -yfq   2>&1) # capture all input and output
                 err_buff=$?
               }
               elif ( ( command -v rpm >/dev/null 2>&1; ) && ( command -v dnf >/dev/null 2>&1; ) ) ; then
               {
-                (( DEBUG )) && echo "dnf install ${missing}"
+                if (( DEBUG )) ; then
+                  echo "dnf install ${missing}"
+                fi
                 install_result=$(sudo dnf install ${missing} -y  2>&1) # capture all input and output
-                (( DEBUG )) && echo "dnf install_result"
-
+                if (( DEBUG )) ; then
+                  echo "dnf install_result"
+                fi
                 err_buff=$?
               }
               elif ( command -v brew >/dev/null 2>&1; ) ; then
               {
                 # _run_command brew install ${missing}
-                (( DEBUG )) && echo "brew install"
+                if (( DEBUG )) ; then
+                  echo "brew install"
+                fi
                 su - "${SUDO_USER}" -c "brew install ${missing} "
                 err_buff=$?
               }
@@ -2792,7 +2835,9 @@ function _run_command(){
             # echo $install_result;
             if [[ ! -z "${install_result}" ]] ; then #  && handle_error "${install_result}"
             {
-                (( DEBUG )) && echo "errors install"
+                if (( DEBUG )) ; then
+                  echo "errors install"
+                fi
                 local error_happened=""
                 [[ "${PROCESSOR_ERROR}" == *"MAC"* ]] && [ $err_buff != 0 ] && error_happened="1"
                 [[ "${PROCESSOR_ERROR}" == *"INTEL"* ]] && (( $err_buff != 0 )) && error_happened="1"
@@ -4284,7 +4329,9 @@ function determine_os_and_fire_action() {
   # Check operating systems
   # echo  ${@}
   if [[ "$(uname)" == "Darwin" ]] ; then
-      (( DEBUG )) && echo "Darwin"
+      if (( DEBUG )) ; then
+        echo "Darwin"
+      fi
       # Do something under Mac OS X platform
       if [[ "$(uname -m)" == "x86_64" ]] ; then
       {
@@ -4298,11 +4345,15 @@ function determine_os_and_fire_action() {
       }
       fi
   elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then
-    (( DEBUG )) && echo "Linux"
+    if (( DEBUG )) ; then
+      echo "Linux"
+    fi
     # Do something under GNU/Linux platform
     # Determine OS platform
     local UNAME=$(uname | tr "[:upper:]" "[:lower:]")
-    (( DEBUG )) && echo "UNAME: $UNAME"
+    if (( DEBUG )) ; then
+      echo "UNAME: $UNAME"
+    fi
     local DISTRO=""
     local ID=""
     local VERSION_ID=""
@@ -4314,28 +4365,38 @@ function determine_os_and_fire_action() {
       {
         if ( command -v lsb_release >/dev/null 2>&1; ); then
         {
-          (( DEBUG )) && echo "RELEASE Option: 1"
+          if (( DEBUG )) ; then
+            echo "RELEASE Option: 1"
+          fi
           DISTRO=$(lsb_release -i | cut -d: -f2 | sed s/'^\t'// | head -1)
         }
         else
         {
-          (( DEBUG )) && echo "RELEASE Option: 2"
+          if (( DEBUG )) ; then
+            echo "RELEASE Option: 2"
+          fi
           DISTRO=$(ls -d /etc/[A-Za-z]*[_-][rv]e[lr]* | grep -v "lsb" | cut -d'/' -f3 | cut -d'-' -f1 | cut -d'_' -f1 | head -1)
         }
         fi
       }
       else # Otherwise, use release info file
       {
-        (( DEBUG )) && echo "RELEASE Option: 3"
+        if (( DEBUG )) ; then
+          echo "RELEASE Option: 3"
+        fi
         DISTRO=$(ls -d /etc/[A-Za-z]*[_-][rv]e[lr]* | grep -v "lsb" | cut -d'/' -f3 | cut -d'-' -f1 | cut -d'_' -f1 | head -1)
       }
       fi
     }
     fi
-    (( DEBUG )) && echo "DISTRO:$DISTRO"
+    if (( DEBUG )) ; then
+      echo "DISTRO:$DISTRO"
+    fi
     if [[ -z "$DISTRO" ]]; then  # if empty
     {
-      (( DEBUG )) && echo "DISTRO empty"
+      if (( DEBUG )) ; then
+        echo "DISTRO empty"
+      fi
       # If available, use /etc/os-release to identify distribution
         if [ -f /etc/os-release ]; then
         {
@@ -4420,8 +4481,12 @@ function determine_os_and_fire_action() {
         fi
     }
     fi
-    (( DEBUG )) && echo "FUNCTION_TO_CALL: $FUNCTION_TO_CALL"
-    (( DEBUG )) && echo "uname -i: $(uname -i)"
+    if (( DEBUG )) ; then
+      echo "FUNCTION_TO_CALL: $FUNCTION_TO_CALL"
+    fi
+    if (( DEBUG )) ; then
+      echo "uname -i: $(uname -i)"
+    fi
     # For everything else (or if above failed), just use generic identifier
     unset UNAME
     unset DISTRO
@@ -4878,18 +4943,24 @@ function raise_to_sudo_and_user_home() {
     local -r provider="$USER_HOME/_/clis/execute_command_intuivo_cli/execute_boot_basic.sh"
     local _err=0 bootbasicsource
     if [   -e "${provider}"  ] ; then
-      (( DEBUG )) && echo "$0 execute_command_intuivo_cli/struct_testing load_execute_boot_basic_with_sudo() Loading locally"
+      if (( DEBUG )) ; then
+        echo "$0 execute_command_intuivo_cli/struct_testing load_execute_boot_basic_with_sudo() Loading locally"
+      fi
       bootbasicsource="""$(<"${provider}")"""
       _err=$?
       [ $_err -gt 0 ] &&  echo -e "\n \n  ERROR! Loading execute_boot_basic.sh. running 'source locally' returned error did not download or is empty err:$_err  \n \n  " && exit 1
     else
       if ( command -v curl >/dev/null 2>&1; )  ; then
-        (( DEBUG )) && echo "$0 execute_command_intuivo_cli/struct_testing load_execute_boot_basic_with_sudo() curl Loading execute_boot_basic.sh from the net using curl "
+        if (( DEBUG )) ; then
+          echo "$0 execute_command_intuivo_cli/struct_testing load_execute_boot_basic_with_sudo() curl Loading execute_boot_basic.sh from the net using curl "
+        fi
         bootbasicsource="""$(curl https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/execute_boot_basic.sh  -so -   2>/dev/null )"""  #  2>/dev/null suppress only curl download messages, but keep curl output for variable
         _err=$?
         [ $_err -gt 0 ] &&  echo -e "\n \n  ERROR! Loading execute_boot_basic.sh. running 'curl' returned error did not download or is empty err:$_err  \n \n  " && exit 1
       elif ( command -v wget >/dev/null 2>&1; ) ; then
-        (( DEBUG )) && echo "$0 execute_command_intuivo_cli/struct_testing load_execute_boot_basic_with_sudo() wget Loading execute_boot_basic.sh from the net using wget "
+        if (( DEBUG )) ; then
+          echo "$0 execute_command_intuivo_cli/struct_testing load_execute_boot_basic_with_sudo() wget Loading execute_boot_basic.sh from the net using wget "
+        fi
         bootbasicsource="""$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/execute_boot_basic.sh -O -   2>/dev/null )"""  #  2>/dev/null suppress only wget download messages, but keep wget output for variable
         _err=$?
         [ $_err -gt 0 ] &&  echo -e "\n \n  ERROR! Loading execute_boot_basic.sh. running 'wget' returned error did not download or is empty err:$_err  \n \n  " && exit 1
@@ -4901,7 +4972,9 @@ function raise_to_sudo_and_user_home() {
     [[ -z "${bootbasicsource}" ]] && echo -e "\n \n  ERROR! Loading execute_boot_basic.sh  bootbasicsource did not download or is empty " && exit 1
     local _temp_dir="$(mktemp -d 2>/dev/null || mktemp -d -t 'execute_boot_basic_source')"
     echo "${bootbasicsource}">"${_temp_dir}/execute_boot_basic_source"
-    (( DEBUG )) && echo "$0 execute_command_intuivo_cli/struct_testing load_execute_boot_basic_with_sudo() Temp execute_boot_basic.sh location ${_temp_dir}/execute_boot_basic_source"
+    if (( DEBUG )) ; then
+      echo "$0 execute_command_intuivo_cli/struct_testing load_execute_boot_basic_with_sudo() Temp execute_boot_basic.sh location ${_temp_dir}/execute_boot_basic_source"
+    fi
     source "${_temp_dir}/execute_boot_basic_source"
     _err=$?
     [ $_err -gt 0 ] &&  echo -e "\n \n  ERROR! Loading execute_boot_basic.sh. Occured while running 'source' err:$_err  \n \n  " && exit 1
@@ -4934,7 +5007,9 @@ function enforce_node_is_version(){
   # Sample use:
   # enforce_node_is_version  "12.20.1"
   #
-  (( DEBUG )) && echo "  Checking for node version to be ${1}"
+  if (( DEBUG )) ; then
+    echo "  Checking for node version to be ${1}"
+  fi
   local msg
   msg=$(node --version | cut -c2- | grep "${1}" 2>&1; )
   _err=$?
@@ -4944,7 +5019,9 @@ function enforce_node_is_version(){
     failed "expected ${TESTING} but got <$(node --version)> "
   }
   fi
-  (( DEBUG )) && passed "${TESTING}"
+  if (( DEBUG )) ; then
+    passed "${TESTING}"
+  fi
   return 0
 } # end enforce_node_is_version
 
