added function raise_to_sudo_and_user_home

diff --git a/struct_testing b/struct_testing
--- a/struct_testing
+++ b/struct_testing
@@ -4251,6 +4251,77 @@ function _install_rpm() {
     return 0
 } # end _install_rpm
 
+export raise_to_sudo_and_user_home
+function raise_to_sudo_and_user_home() {
+  #
+  # Sample usage:
+  #
+  # Place this on the start of the script  that 
+  #  needs to reloaded as sudo "MOTHER" script:
+  #
+  #   export  THISSCRIPTCOMPLETEPATH
+  #   typeset -gr THISSCRIPTCOMPLETEPATH="$(basename "$0")"   # § This goes in the FATHER-MOTHER script 
+  #   export _err 
+  #   typeset -i _err=0 
+  #
+  # ...
+  # then call it 
+  # ...
+  #
+  #   raise_to_sudo_and_user_home
+  #   [ $? -gt 0 ] && failed to raise_to_sudo_and_user_home 
+  #   enforce_variable_with_value USER_HOME "${USER_HOME}"
+  #
+  load_execute_boot_basic_with_sudo(){
+    # shellcheck disable=SC2030
+    if ( typeset -p "SUDO_USER"  &>/dev/null ) ; then
+    {
+      export USER_HOME
+      # typeset -rg USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)  # Get the caller's of sudo home dir Just Linux
+      # shellcheck disable=SC2046
+      # shellcheck disable=SC2031
+      typeset -rg USER_HOME="$(echo -n $(bash -c "cd ~${SUDO_USER} && pwd"))"  # Get the caller's of sudo home dir LINUX and MAC
+    }
+    else
+    {
+      local USER_HOME=$HOME
+    }
+    fi
+    local -r provider="$USER_HOME/_/clis/execute_command_intuivo_cli/execute_boot_basic.sh"
+    echo source "${provider}"
+    # shellcheck disable=SC1090
+    [   -e "${provider}"  ] && source "${provider}"
+    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/execute_boot_basic.sh -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
+    if ( command -v failed >/dev/null 2>&1; ) ; then
+    {
+      return 0
+    }
+    else
+    {
+      echo -e "\n \n  ERROR! Loading execute_boot_basic.sh \n \n "
+      exit 1;
+    }
+    fi
+    return 0
+  } # end load_execute_boot_basic_with_sudo
+
+  load_execute_boot_basic_with_sudo
+  _err=$?
+  if [ $_err -ne 0 ] ;  then
+  {
+    >&2 echo -e "ERROR There was an error loading load_execute_boot_basic_with_sudo Err:$_err "
+    exit $_err
+  }
+  fi
+
+  # Overwrite trap
+  # function _trap_on_exit(){
+    # echo -e "\033[01;7m*** TRAP $THISSCRIPTCOMPLETEPATH EXITS ...\033[0m"
+  # }
+  #trap kill ERR
+  # trap _trap_on_exit EXIT
+  #trap kill INT
+} # end raise_to_sudo_and_user_home
 
 
 
